### ISSUE TITLE
Automatically detect when new drives are added and when they are removed

### ISSUE THREAD

**Issue by wlan0** [minio/directpv#236]

**Comment by ramvarra** [comment]
Is there a work-around to discover new drives without  uninstalling/reinstalling the plugin?

**Comment by Praveenrajmani** [comment]
> Is there a work-around to discover new drives without uninstalling/reinstalling the plugin?

in directpv v3.0.0, dynamic-discovery feature has been made default. This feature will automatically detect the drive additions and removals. Please install/upgrade to directpv v3.0.0
