### ISSUE TITLE
wrong slashes in deployment and daemonset and new drives doesn't appear automatically only after reinstallation  

### ISSUE THREAD

**Issue by HaykManukyanAvetiky** [minio/directpv#375]
on Windows machine when I try to install direct CSI with following command
` kubectl direct-csi install --crd `
It stacks at the following point 
![image](https://user-images.githubusercontent.com/65945812/132458798-f02e979c-2b4a-45bd-a717-5455b6c52553.png)
The reason is that it cant create deployment 
![image](https://user-images.githubusercontent.com/65945812/132458950-b2824704-84f3-45c0-8557-b50946775f80.png)
and the reason why it can't deploy is wrong slashes in image name.
When I am running following command 
`  kubectl edit deployment -n direct-csi-min-io directcsi-conversion-webhook ` 
I see this lines in YAML file 
![image](https://user-images.githubusercontent.com/65945812/132459283-1fbc1037-8401-49ec-b255-4c65251e79b6.png)
as you can see the reason is slashes , after changing them everything becomes ok and the installation is continuing.
 - The same problem with deployment direct-csi-min-io and  daemonset direct-csi-min-io.
 - Also 
 - - Krew installs version 1.4.2 but 1.4.3 is already released as far as I understand. 
 - - I would like to have update feature in directCSI 
 - - It would be great to have drive discovery command, currently I have to uninstall and install directCSI every time in order to see new drives

**Comment by HaykManukyanAvetiky** [comment]
BTW I am using windows machine but my kube cluster on Linux of course, with 3 manager and 3 worker

**Comment by Praveenrajmani** [comment]
Fixed in https://github.com/minio/directpv/pull/618
