### ISSUE TITLE
Partition not listed

### ISSUE THREAD

**Issue by flatrow** [minio/directpv#398]
Hi,
I have an installation of Kubernetes v1.20.2 with kube-apiserver --allow-privileged=true, flannel, metallb and direct-csi.
One node (vm152957.local) has partitions:
```
# lsblk
NAME   MAJ:MIN RM SIZE RO TYPE MOUNTPOINT
vda    252:0    0  64G  0 disk 
├─vda1 252:1    0  30M  0 part 
├─vda2 252:2    0   8G  0 part /
└─vda3 252:3    0  56G  0 part /data
```
But drives command doesn't list /dev/vda3 partition:
```
% k direct-csi --kubeconfig ~/.kube/k1 drives ls --all
 DRIVE      CAPACITY  ALLOCATED  FILESYSTEM  VOLUMES  NODE            ACCESS-TIER  STATUS          
 /dev/vda2  8.0 GiB   4.3 GiB    ext4        -        vm152950.local  -            Unavailable     
 /dev/vda2  8.0 GiB   2.9 GiB    ext4        -        vm152951.local  -            Unavailable     
 /dev/vda2  8.0 GiB   2.7 GiB    ext4        -        vm152957.local  -            Unavailable
``` 
When I attach to corresponding container direct-csi-min-io-##### the output of lsblk differs (/dev/vda3 not mounted):
```
# lsblk
NAME   MAJ:MIN RM SIZE RO TYPE MOUNTPOINT
vda    252:0    0  64G  0 disk 
├─vda1 252:1    0  30M  0 part 
├─vda2 252:2    0   8G  0 part /var/lib/kubelet/pods
└─vda3 252:3    0  56G  0 part 
```
I tried to analyse repository code but I'm not a Go developer and actually newbie in Kubernetes. I noticed usage of /proc/1/mounts that are filtered then, the outputs are
```
#cat /proc/1/mounts | grep /dev/vda
/dev/vda2 / ext4 rw,relatime,errors=remount-ro,stripe=32593 0 0
/dev/vda3 /data ext4 rw,relatime 0 0
```
```
# cat /proc/mounts | grep /dev/vda
/dev/vda2 /csi ext4 rw,relatime,errors=remount-ro,stripe=32593 0 0
/dev/vda2 /etc/hostname ext4 rw,relatime,errors=remount-ro,stripe=32593 0 0
/dev/vda2 /etc/hosts ext4 rw,relatime,errors=remount-ro,stripe=32593 0 0
/dev/vda2 /etc/resolv.conf ext4 rw,relatime,errors=remount-ro,stripe=32593 0 0
/dev/vda2 /var/lib/direct-csi ext4 rw,relatime,errors=remount-ro,stripe=32593 0 0
/dev/vda2 /var/log/driver-termination-log ext4 rw,relatime,errors=remount-ro,stripe=32593 0 0
/dev/vda2 /var/lib/kubelet/plugins ext4 rw,relatime,errors=remount-ro,stripe=32593 0 0
/dev/vda2 /var/lib/kubelet/pods ext4 rw,relatime,errors=remount-ro,stripe=32593 0 0
```
I assume this is a problem, but don't know what to do with this and whether this is related to used csi sock or to Kubernetes configuration.
So I would really appreciate any advice.

**Comment by wlan0** [comment]
Hi @flatrow,

Thanks for sharing detailed information. The reason we don’t show it is because the drive is already mounted I.e. a signal to us that we shouldn’t manage that drive. We are very sensitive with data, and we don’t want to make it easy for users to overwrite or format their data even by mistake. 

If you run `kubectl direct-csi drives ls -a`, which turns on the `--all` flag, you’ll be able to /dev/vda3 too. It’ll show up as “Unavailable”.

If you want direct-csi to manage that drive as well, please unmount that drive, and restart direct-csi pods on that node. 

The manual unmounting step is not needed if the drive is managed by direct-csi itself. This is because we have checks and balances in place to ensure that no drives InUse can be formatted. We only expect the manual step for drives that are mounted and managed outside of direct-csi.

**Comment by romqn1999** [comment]
I have same issue.
The output of `lsblk`:
```sh
$ lsblk
NAME   MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
sda      8:0    0   1,8T  0 disk 
├─sda1   8:1    0   994G  0 part /
├─sda2   8:2    0     1K  0 part 
├─sda3   8:3    0 868,1G  0 part /mnt/sda3
└─sda5   8:5    0   976M  0 part
```
The output of `cat /proc/mounts | grep /dev/sda` is same as the output of `cat /proc/1/mounts | grep /dev/sda`:
```sh
$ cat /proc/mounts | grep /dev/sda
/dev/sda1 / ext4 rw,relatime,errors=remount-ro 0 0
/dev/sda3 /mnt/sda3 ext4 rw,relatime 0 0
```
And the output of `kubectl direct-csi drives ls -a -n machine-01`:
```sh
$ kubectl direct-csi drives ls -a -n machine-01
 DRIVE      CAPACITY  ALLOCATED  FILESYSTEM  VOLUMES  NODE        ACCESS-TIER  STATUS          
 /dev/sda1  994 GiB   384 GiB    ext4        -        machine-01  -            Unavailable
```
And I use direct-csi version v1.4.3:
```sh
$ kubectl direct-csi --version
direct-csi version v1.4.3
```
Can you hep me to solve the issue.
