### ISSUE TITLE
implement topology for minio pods

### ISSUE THREAD

**Issue by mjosipovic1979** [minio/directpv#464]
hi team

i want to use minio operator to install minio distributed cluster using local drives on three (3) worker nodes. Every worker has 6 drives (total 18). As distributed setup reqs. (node=4 or more) we are trying to install 6 node (2 per worker) with 3 disks on each (for total 18). we are using directcsi minio as per recommendation, but having problems to schedule pods on right nodes (pod afinity, node selector etc). 

if we can implement some logic (zone, rack, failire-domain ...) it would be posible to deploy six (6) minio pods each with three (3) drives and schedule minio pods and pvc/pv on right machine so it can survive one k8s worker (k8s-lab-s1/2/3) failure. 
one k8s worker failure would bring down 2 minio pods or total 6 drive (cluster total is 18) so we should have write quorum.

Thanks.

Direct-CSI version
quay.io/minio/direct-csi:v1.4.6
kubectl-direct_csi drives ls |grep -i ready
/dev/sdd 1.1 TiB 8.4 GiB xfs - k8s-lab-s1 - Ready
/dev/sde 1.1 TiB 8.4 GiB xfs - k8s-lab-s1 - Ready
/dev/sdf 1.1 TiB 8.4 GiB xfs - k8s-lab-s1 - Ready
/dev/sdg 1.1 TiB 8.4 GiB xfs - k8s-lab-s1 - Ready
/dev/sdh 1.1 TiB 8.4 GiB xfs - k8s-lab-s1 - Ready
/dev/sdi 1.1 TiB 8.4 GiB xfs - k8s-lab-s1 - Ready
/dev/sdd 1.1 TiB 8.4 GiB xfs - k8s-lab-s2 - Ready
/dev/sde 1.1 TiB 8.4 GiB xfs - k8s-lab-s2 - Ready
/dev/sdf 1.1 TiB 8.4 GiB xfs - k8s-lab-s2 - Ready
/dev/sdg 1.1 TiB 8.4 GiB xfs - k8s-lab-s2 - Ready
/dev/sdh 1.1 TiB 8.4 GiB xfs - k8s-lab-s2 - Ready
/dev/sdi 1.1 TiB 8.4 GiB xfs - k8s-lab-s2 - Ready
/dev/sdd 1.1 TiB 8.4 GiB xfs - k8s-lab-s3 - Ready
/dev/sde 1.1 TiB 8.4 GiB xfs - k8s-lab-s3 - Ready
/dev/sdf 1.1 TiB 8.4 GiB xfs - k8s-lab-s3 - Ready
/dev/sdg 1.1 TiB 8.4 GiB xfs - k8s-lab-s3 - Ready
/dev/sdh 1.1 TiB 8.4 GiB xfs - k8s-lab-s3 - Ready
/dev/sdi 1.1 TiB 8.4 GiB xfs - k8s-lab-s3 - Ready

kubectl-direct_csi info

NODE CAPACITY ALLOCATED VOLUMES DRIVES
• k8s-lab-s1 6.5 TiB 0 B 0 6
• k8s-lab-s2 6.5 TiB 0 B 0 6
• k8s-lab-s3 6.5 TiB 0 B 0 6

0 B/20 TiB used, 0 volumes, 18 drives

**Comment by wlan0** [comment]
> if we can implement some logic (zone, rack, failire-domain ...) it would be posible to deploy six (6) minio pods each with three (3) drives and schedule minio pods and pvc/pv on right machine so it can survive one k8s worker (k8s-lab-s1/2/3) failure.

Hi @mjosipovic1979, You could add affinity rules into your pod specs directly that specify the appropriate zones/racks etc. 

direct-csi will automatically provide you volumes only from nodes that satisfy the affinity constraints

**Comment by wlan0** [comment]
If you are asking about topology from operator, let me bring in @harshavardhana for this

**Comment by Praveenrajmani** [comment]
> but having problems to schedule pods on right nodes (pod afinity, node selector etc).

pod and node affinity can be provided in the tenant config. please refer https://docs.min.io/minio/k8s/tenant-management/manage-minio-tenant.html#manage-a-minio-tenant for more details

> schedule minio pods and pvc/pv on right machine
