### ISSUE TITLE
How to set replicas num of `deployment.apps/directcsi-conversion-webhook` and `deployment.apps/directcsi-conversion-webhook`

### ISSUE THREAD

**Issue by tanguofu** [minio/directpv#478]
we need  deploy  `direct-csi` on one single k8s node, it is better to scale the deployment replicas to 1, because there is limit of max pods in single node.

and is there can add args to  `kubectl direct_csi install ` ?

many thanks.

**Comment by Praveenrajmani** [comment]
you can also configure deployment replicas manually. Eg,  `kubectl edit deployment <deployment_name> -n direct-csi-min-io`
