### ISSUE TITLE
Pods unbound in Openshift 4.9

### ISSUE THREAD

**Issue by ShayBenyo11** [minio/directpv#492]
Environments: Kubernetes 1.22, Openshift 4.9
Tested with both 1.4.3 and 1.4.6 CSI versions 

Issue: 
None of the CSI pods throw any errors nor the API servers, PVCs that are created ARE bounded to DirectCSI PVs yet for some unknown reasons application pods with those PVCs are stuck on CreatingContainer with the following errors:
`0/1 nodes are available: 1 pod has unbound immediate PersistentVolumeClaims` 
&
`Unable to attach or mount volumes: unmounted volumes=[application], unattached volumes=[app-tls kube-api-access-rbbht 0 1]: timed out waiting for the condition`
&
`AttachVolume.Attach failed for volumes "pvc-........."`

ALSO, you could see the PVC in the Volumes of the pod. And for Openshift 4.8  (Kubernetes 1.19) DirectCSI worked perfectly fine.
So my questions are: 
Is DirectCSI/PV at all compatiable or supported with those Openshift & Kubernetes versions?
If so, what's going wrong? I'm kinda lost on this one 

Thank you!

**Comment by Praveenrajmani** [comment]
>  AttachVolume.Attach failed for volumes "pvc-........."

Can you paste the full error message? Also, can you paste the error logs in respective PVCs of those pods in container creating phase?

> And for Openshift 4.8 (Kubernetes 1.19) DirectCSI worked perfectly fine
Do you mean it worked fine with k8s 1.19 + Openshift 4.8?

> 0/1 nodes are available
Looks like, the volumes were asked to be scheduled on wrong nodes where direct-csi is not running. You need to provide necessary affinity rules to the pods to schedule volumes on the correct nodes.

**Comment by ShayBenyo11** [comment]
> > AttachVolume.Attach failed for volumes "pvc-........."
> 
> Can you paste the full error message? Also, can you paste the error logs in respective PVCs of those pods in container creating phase?
> 
> > And for Openshift 4.8 (Kubernetes 1.19) DirectCSI worked perfectly fine
> 
> Do you mean it worked fine with k8s 1.19 + Openshift 4.8?
> 
> > 0/1 nodes are available
> 
> Looks like, the volumes were asked to be scheduled on wrong nodes where direct-csi is not running. You need to provide necessary affinity rules to the pods to schedule volumes on the correct nodes. Or you can taint these particular nodes which is not meant for volumes to be scheduled on.

@Praveenrajmani Thank you for the quick reply!

1. It just mentions the name of the PVC  so that's why I didn't post it all
2. Yes
3. So I was looking into it too, the default Affinity rules added to the PVs actually looked fine with labels attached to the Node. Or maybe I should look at something else that's isnt the PV?

**Comment by Praveenrajmani** [comment]
If you look into the output of `kubectl describe pvc` you can see the annotation - `/selected-node`. Check if it is the correct node and direct-csi is running in this node. @ShayBenyo11

**Comment by Praveenrajmani** [comment]
in directPV, PVs will be dynamically created. You need to look into node affinity rules and its respective PVCs @ShayBenyo11

**Comment by ShayBenyo11** [comment]
> If you look into the output of `kubectl describe pvc` you can see the annotation - `/selected-node`. Check if it is the correct node and directPV is running in this node. @ShayBenyo11

Ha, I can't see this annotation at all. Only bind-completed and bound-by-controller (which are both yes) and storage-provisioner. 
It's a single-node openshift (also the 4.8 I said it worked on), so it's definitely running on this one yet it is weird there's no such annotation.
I also tried creating a PV with different affinity - simple as hostname and the container is still stuck on ContainerCreating and is timed out.

**Comment by Praveenrajmani** [comment]
> I can't see this annotation at all

This means k8s could not assign a node for that PVC.

>  I also tried creating a PV with different affinity - simple as hostname and the container is still stuck on ContainerCreating and is timed out.

Did you try with localPV as well?

> Why can't directpv attach the volume to the node?

DirectPV did not receive a request in the first place, We might want to check the kubelet logs

**Comment by Praveenrajmani** [comment]
Can you also get us some info for further investigation,

```
- kubectl direct-csi volumes ls --all -o yaml > /tmp/volumes.yaml
- logs of pods in direct-csi-min-io namespace (container name - direct-csi)
- kubectl get csinodes -o wide
- kubectl get nodes -o wide
```

**Comment by ShayBenyo11** [comment]
> > I can't see this annotation at all
> 
> This means k8s could not assign a node for that PVC.
> 
> > I also tried creating a PV with different affinity - simple as hostname and the container is still stuck on ContainerCreating and is timed out.
> 
> Did you try with localPV as well?

You mean configure Local Persistent Volumes on disks? 

> > Why can't directpv attach the volume to the node?
> 
> DirectPV did not receive a request in the first place, We might want to check the kubelet logs

Well, the CSI logs do show that requested volumes or creations are answered successfully, in general it shows as if eveything is fine and working. Or should it receive more requests also after doing so?

**Comment by ShayBenyo11** [comment]
**Logs:** 
(So sorry I can't just paste them. it's an air-gapped environment and no way to get it out so if there's need to show anything else from those pods then just tell, I shot what seemed relevant)

**volumes:**
Looks like this for all volumes
![image](https://user-images.githubusercontent.com/84469682/148193364-03e70740-b7d1-4d71-9747-d98c8209c1be.png)

**direct-csi pod:**
conversion-webhook pods show no logs

leader:
![image](https://user-images.githubusercontent.com/84469682/148193034-34ddad42-ae54-45e0-bb03-8acbdc0507fa.png)


**kubectl get csinodes -o wide:**
Can't show the hostname but it says 1 Drivers.

**kubectl get nodes -o wide**

ROLES: master,worker 
VERSION: v1.22.0-rc0+894a78b
IMAGE: RHEL CoreOS 49.84 
KERNEL-VERSION: 4.8.10 
CONTAINER-RUNTIME: cri-o://1.22.0-73.rhaos4.9

**Comment by Praveenrajmani** [comment]
what does `kubectl direct-csi drives ls` say @ShayBenyo11 ? Can  you paste the output of this and also `kubectl direct-csi info`

**Comment by Praveenrajmani** [comment]
closing this stale issue
