### ISSUE TITLE
Can not reinstall direct-csi 

### ISSUE THREAD

**Issue by btlam87** [minio/directpv#498]
Hi, i am new in direct-csi old name of directpv, i installed direct-csi by command: kubectl krew install direct-csi then kubectl direct-csi install --crd, everything worked perfectly.

But i tried to uninstall by: kubectl direct-csi uninstall and want to reinstall it and i got this error: ERROR serviceaccounts "direct-csi-min-io" is forbidden: unable to create new content in namespace direct-csi-min-io because it is being terminated.

My version is: direct-csi  v2.0.1

Please, tell me what should i do? keep waiting or what solution for me.

**Comment by Praveenrajmani** [comment]
Can you give it some time? looks like some of the pods in 'direct-csi-min-io` are still not cleaned up. 

`kubectl get all -n direct-csi-min-io` can tell if the pods are still up. If so, you can force delete them or execute `kubectl direct-csi uninstall` again.

**Comment by btlam87** [comment]
I can install direct-csi again, something wrong with calico-apiserver then after restart it, then install successfully. Now i got new issue when check: kubectl get all --namespace direct-csi-min-io -o wide, pods running on worker nodes have status "Running" but on my master node it's status is "ContainerCreating".

**Comment by Praveenrajmani** [comment]
can you describe the pod and see? @btlam87

**Comment by btlam87** [comment]
Yes, but Events are <none>

**Comment by Praveenrajmani** [comment]
yeah, you can give it a try but that shouldn't be related.

can you check the resource limits in master nod? this should be related to the node spec/limitations. Also, try deploying a "hello-world" pod in master and see if this works
