### ISSUE TITLE
[QUESTION] How to grow/extend the filesystem when the disk got resized?

### ISSUE THREAD

**Issue by WolfspiritM** [minio/directpv#519]
As our data is growing we're using virtual disks that can grow in size.
Currently we're using a "self managed" drive and there we just use xfs_growfs to increase the size of the filesystem.

We'd however move over to using directpv as we're starting to use kubernetes.

Does directpv support that or can we just use xfs_growfs on the block device?

**Comment by balamurugana** [comment]
With the latest release v2.0.2, you could enable dynamic drive discovery at install time which handles drive changes. However currently there is no support for `xfs_growfs` i.e. it should be done manually by the admin.
