### ISSUE TITLE
old version of direct-csi(v1.4.6-rhel7) leaks when it fails to mount a volume

### ISSUE THREAD

**Issue by jeffguorg** [minio/directpv#520]
Hi,

we were using direct-csi in one of our staging k8s environment. one day the cluster failed for some stupid operations done by me, and get recovered after a while, but since then direct-csi cannot mount the volume and says there is no space left.

direct-csi container logs show `failed to set quota for device: /var/lib/direct-csi/devices/e1a8299c-c2ea-46f9-8627-93c7d87b6b95 error: no such device` at first. and then it says `failed stage volume: no space left on device` after a while.

for now, i found that there is countless mountpoint on this host. i think that is why there is `no space left on device`. output of mount command looks like this: https://pastebin.com/yXb2ZJmQ

Not sure if this is fix in new version of direct-csi/directpv and did not find a similar issue. 

OS: CentOS 7
Direct-CSI: v1.4.6-rhel7

BTW, the drive is something like this: Volume: https://pastebin.com/JNniE53D Drive: https://pastebin.com/aYxk3nSJ
it is weird to have a `driveStatus: Terminating`. i didn't delete or change it by hand at that time not did i delete the pvc or pv. why is it Terminating? can it get fixed by changing values in etcd?

**Comment by balamurugana** [comment]
1. Please try the latest version optionally with dynamic drive discovery and reopen the issue if the problem exhibits.
2. Open separate github issues and avoid single github issue for multiple problems.
