### ISSUE TITLE
Using volumes provided by directpv causes network errors

### ISSUE THREAD

**Issue by pinknemo452** [minio/directpv#529]
I installed minio operator and as recomended I used directpv to provision PV. Next, I tried to test it with mint(github.com/minio/mint). I successfully created a tenant with volumes provided by directpv, ran tests and they failed with network errors (mint and node are located in the local network)
[first_tets_logs.txt](https://github.com/minio/directpv/files/8034918/first_tets_logs.txt)
[third_tets_logs.txt](https://github.com/minio/directpv/files/8034919/third_tets_logs.txt)
[second_tets_logs.txt](https://github.com/minio/directpv/files/8034920/second_tets_logs.txt)

so I tried testing with other csi and localpath volumes, with them tests succsesfully passed
[successfully_passed_tests.txt](https://github.com/minio/directpv/files/8034967/successfully_passed_tests.txt)

Dynamic PV provisioning and minio tenant( storing files in buckets) works, but I cant get why tests fails only when volumes provided by directpv.

**Comment by Praveenrajmani** [comment]
I see `connect: no route to host` errors in the logs pasted @pinknemo452 . If you are port-forwarding, then the connection should've been intermittent. Or the coredns is probably crashing or over dumped. 

anyway, these network errors is not related to directpv. it doesn't deal with any k8s networking.
