### ISSUE TITLE
Can't probe devices

### ISSUE THREAD

**Issue by hlj** [minio/directpv#537]
I have a k8s cluster on centos 7.6, when install directpv , I met a problem:

When I install directpv with  dynamic drive discovery flag that can't get the drives list.
This has a error in directpv-drive-discovery container's log: 
```
E0301 05:41:37.349492   14862 uevent.go:189] "unable to probe devices" err="open /dev/fd0: no such device or address"
```
When not use dynamic drive discovery, the direct-csi container get same error.

This's my install command:
```sh
    kubectl directpv install -r registry.czinfo.net -n "app-type/minio=true" --enable-dynamic-discovery
```

What's wrong with me?

**Comment by hlj** [comment]
current status:

```sh
master@MacBook-Pro minio-install % kubectl directpv info      
 NODE                CAPACITY  ALLOCATED  VOLUMES  DRIVES 
 • czeic-worker-11  -         -          -        -      
 • czeic-worker-12  -         -          -        -      
 • czeic-worker-13  -         -          -        -      
 • czeic-worker-14  -         -          -        -      
master@MacBook-Pro minio-install % kubectl directpv drives ls
 DRIVE  CAPACITY  ALLOCATED  FILESYSTEM  VOLUMES  NODE  ACCESS-TIER  STATUS   
master@MacBook-Pro minio-install % 
```

**Comment by hlj** [comment]
when remove the floppy device, this problem resolved.   
REF: https://access.redhat.com/discussions/2355851

**Comment by harshavardhana** [comment]
> What's wrong with me?

Using floppy drives!
