### ISSUE TITLE
Unable to see drives with directpv 2.0.4 on Centos 7.9

### ISSUE THREAD

**Issue by kaplanlior** [minio/directpv#538]
Hi MinIO team,

I'm happy to use your software :)

I have a few k8s nodes with local disks already formatted with FS and mounted.
I can see them as "Unavailable" with drives list --all.

While the documentation says "Unavailable drives cannot be formatted" I wonder what should I do in order to make them available again? I've unmounted them, used wipefs utility to remove the FS and still they appear unavailable in "kubectl directpv drives ls".

I have a k8s cluster (v1.19.4) running on Centos 7.9 (mentioning in case #407 is also relevant) with directpv (since I saw the deprecation message in direct-csi)

```
# kubectl directpv --version
directpv version v2.0.4

**Comment by balamurugana** [comment]
After drives are unmounted, please restart DirectPV pods. This will catch all disk changes. Reopen this issue if any problem is seen after that.
