### ISSUE TITLE
Minor version parsing issues

### ISSUE THREAD

**Issue by djkelleher** [minio/directpv#549]
My k8s version says "1.22+" and it causes this error `ERROR unsupported kubernetes version 1.22+` because the installer checks for minor versions "18", "19", "20", "21", "22" (i.e. versions with no "+"). Are "+" versions something that support should be added for?

**Comment by Praveenrajmani** [comment]
this is fixed in https://github.com/minio/directpv/pull/534 and relased

please upgrade to the latest version. the upgrade steps are defined in https://github.com/minio/directpv#upgrade
