### ISSUE TITLE
livenessprobe Connection to unix:///csi/csi.sock

### ISSUE THREAD

**Issue by ooraini** [minio/directpv#550]
I have been using directpv for a few weeks. Everything is working perfectly. I recently started collecting all my container logs and then noticed a high volume of logs from directpv with the same message:
```
connection.go:153] Connecting to unix:///csi/csi.sock
```

The logs are from the daemonset container `liveness-probe`. 

I'm running Rocky Linux 8.5 with directpv 2.0.4. I have concluded that the issue is not related to SELinux.

The csi.sock exists in `/var/lib/kubelet/...` and I can connect to it using `socat`.

Unfortunately, the container contains no shell. I did check the pod manifest and it does contain the volume mount for socket folder.

All other containers have no errors or warnings.

Note that everything is working as expected.

**Comment by Praveenrajmani** [comment]
> Connecting to unix:///csi/csi.sock

This means that the kubelet still tries to communicate and register the csi driver. There could also be intermittent logs pointing to n/w failures here. 

If you wish to reduce the verbosity here, you can edit the directpv deamonset and set the verbosity to some value < 3 in the container.  

there is an another way to reduce the verbosity, 

```
kubectl directpv uninstall
kubectl directpv install --dry-run > directpv.yaml
(make changes in the yaml - set the `-v=2`)
kubectl apply -f directpv.yaml
```

**Comment by Praveenrajmani** [comment]
also, check the kubelet logs as well. 

If you see some errors leading to volume mount clean-ups for orphaned logs, you need to upgrade your kubernetes then - (https://github.com/kubernetes/kubernetes/pull/102576)

**Comment by Praveenrajmani** [comment]
as a best practice, you can use log rotate to cleanup logs regularly
