### ISSUE TITLE
on arm64 CPU: exec /livenessprobe: exec format error 

### ISSUE THREAD

**Issue by masknu** [minio/directpv#551]
Thank you for creating this project. 
I followed installing instructions on [Custom Installation](https://github.com/minio/directpv/blob/master/docs/installation.md), found that pod is end with error:
```
# kubectl describe pod direct-csi-min-io-4lglc -n direct-csi-min-io
```
```
Controlled By:  DaemonSet/direct-csi-min-io
    Last State:  Terminated
      Reason:    Error
      Message:   exec /livenessprobe: exec format error
```
It seems like those pod pulling from [csi-node-driver-registrar](quay.io/minio/csi-node-driver-registrar@sha256:843fb23b1a3fa1de986378b0b8c08c35f8e62499d386de8ec57801fd029afe6d) is not compatible with arm64 CPU.

**Comment by Praveenrajmani** [comment]
you can pick the corresponding plugin binary here - https://github.com/minio/directpv/releases/tag/v2.0.7.

the plugin binaries are prefixed by `kubectl-`
