### ISSUE TITLE
ERROR unsupported kubernetes version 1.20+

### ISSUE THREAD

**Issue by eagle9527** [minio/directpv#552]
eagle@Computer ~ % kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5", GitCommit:"c285e781331a3785a7f436042c65c5641ce8a9e9", GitTreeState:"clean", BuildDate:"2022-03-16T15:58:47Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.6-tke.12", GitCommit:"1cb721e6058b081fee879989b8616081cf147bb6", GitTreeState:"clean", BuildDate:"2022-01-14T02:05:16Z", GoVersion:"go1.15.10", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.23) and server (1.20) exceeds the supported minor version skew of +/-1
eagle@Computer ~ % kubectl directpv install  
I0321 11:34:08.699933    6101 install.go:95] Enable dynamic drive change management using --enable-dynamic-discovery flag
W0321 11:34:08.700052    6101 install.go:97] dynamic-discovery feature is strictly experimental and NOT production ready yet
ERROR unsupported kubernetes version 1.20+
eagle@Computer ~ %

**Comment by Praveenrajmani** [comment]
this is fixed in https://github.com/minio/directpv/pull/534 and relased

please upgrade to the latest version. the upgrade steps are defined in https://github.com/minio/directpv#upgrade

**Comment by eagle9527** [comment]
@Praveenrajmani 
HI：
         directpv  version  v2.0.7
          ``` kubectl directpv --version
                directpv version v2.0.7 ```

**Comment by eagle9527** [comment]
````
eagle@Computer web % kubectl directpv --version    
directpv version v2.0.7
eagle@Computer web % k get nodes                   
NAME          STATUS   ROLES    AGE   VERSION
10.206.0.17   Ready    <none>   18d   v1.20.6-tke.12
10.206.0.6    Ready    <none>   18d   v1.20.6-tke.12
````

**Comment by djkelleher** [comment]
> this is fixed in #534 and released
> 
> please upgrade to the latest version. the upgrade steps are defined in https://github.com/minio/directpv#upgrade

@Praveenrajmani 
I do have the latest version. It looks like #534 is for EKS only. I was using a local microk8s instance.

Are there versions that should be disallowed based on the vendor? Or should the check used in the installer be something vendor agnostic, such as extracting the version with a regex pattern (e.g. `(?:^|[^\d])1\.(1[8-9]|2[0-2])(?:[^\d]|$)`)

**Comment by eagle9527** [comment]
I am the kubernetes version provided by Tencent and cannot be installed

**Comment by Praveenrajmani** [comment]
ah i see, we will fix this in the next release
