### ISSUE TITLE
Implement disk allow list

### ISSUE THREAD

**Issue by pkoetsier** [minio/directpv#553]
Currently directpv probes all block devices. We would prefer to instead be able to specify the disks which directpv should concern itself with for the following reasons:

- Our worker nodes have a large number of block devices managed by another CSI and only a small number of DAS devices which we would like to manage with directpv. Specifying the DAS devices for instance using /dev/disk/by-id paths would eliminate the risk of someone formatting the wrong devices during operation.
- Our worker nodes have block devices which cannot be read. That's because these are stand-by LUN replicas.
- Our worker nodes now and then have block devices for which an open() will fail with ENXIO (No such device or address). This for instance happens during FC rezoning changes.

Would it be possible to add an allowlist feature to directpv which would make it possible to specify which block devices directpv should probe?

Directpv 2.0.7 crashes on the disk open and disk read errors mentioned above. Also see #539 which my colleague created for this. We are currently working around this using the following ugly hack which adds an open and a read test to getHidden():

```
--- a/pkg/sys/drive_discovery_linux.go
+++ b/pkg/sys/drive_discovery_linux.go
@@ -253,7 +253,24 @@ func getHidden(name string) bool {
        // borrow idea from 'lsblk'
        // https://github.com/util-linux/util-linux/commit/c8487d854ba5cf5bfcae78d8e5af5587e7622351
        v, _ := readFirstLine("/sys/class/block/"+name+"/hidden", false)
-       return v == "1"
+    if v == "1" {
+        return true
+    }
+
+    devFile, err := os.Open("/dev/"+name)
+    if err != nil {
+        klog.Errorf("getHidden(): open failed on %s -> setting hidden: %s", name, err)
+        return true
+    }
+    defer devFile.Close()
+
+    data := make([]byte, 512)
+    if _, err := devFile.Read(data); err != nil {
+        klog.Errorf("getHidden(): read failed on %s -> setting hidden: %s", name, err)
+        return true
+    }
+
+     return false
 }
 
 func getPartitions(name string) ([]string, error) {
```

**Comment by Praveenrajmani** [comment]
> Directpv 2.0.7 crashes on the disk open and disk read errors mentioned above. Also see https://github.com/minio/directpv/issues/539 which my colleague created for this. We are currently working around this using the following ugly hack which adds an open and a read test to getHidden():

yeah, we are currently refactoring the drive discovery mechanism which covers these concerns. Even if one of the drive fails during the probe, it would continue to probe other devices without stopping.

currently, it is in testing phase and should be released soon.

**Comment by obacak** [comment]
Dear @Praveenrajmani,

Thanks for your feedback.
We are wondering if the project would consider implementing `--disk-allow-list` feature as my colleague described above?
