### ISSUE TITLE
direct-csi installation failed

### ISSUE THREAD

**Issue by pjy324** [minio/directpv#556]
I installed directpv in my kubernities environment.

Only certain nodes are experiencing CrashLoopBackOff.
After uninstalling, reinstalling causes problems on the same node.
![pod_info](https://user-images.githubusercontent.com/101962308/159499563-93d24694-91ca-4eec-a052-cdfdc2b9c7b0.PNG)

We checked the 'direct-csi' log of the node in which the problem occurs.
As healthz API timeout occurred five times, direct-csi container seems to have failed to execute.

Do you know how to solve this problem?
![log](https://user-images.githubusercontent.com/101962308/159501405-d17e65f2-1c71-40a0-ac6b-400b7335eba8.PNG)

**Comment by Praveenrajmani** [comment]
the coredns is not working in this node. the service endpoint is not reachable. please check if your coredns is swamped or not running.
