### ISSUE TITLE
Containerd overlay snapshotter filling up

### ISSUE THREAD

**Issue by WolfspiritM** [minio/directpv#564]
Hi,

I'm using directpv to map two local drives to the minio container in kubernetes.
This does work fine but after extensive testing I noticed that my root filesystem is filling up cause of containerd snapshots (I've not configured any snapshots).

Did I miss some configuration here?
All of the minio files seem to be replicated in that folder structure.

I have the feeling that containerd does some kind of container snapshots and copys all the files from the pvc into that snapshot.

```
root@k8stestworker01:/var/lib/rancher/rke2/agent/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/10467/fs# ls -la
total 48
drwxr-xr-x 10 root root   4096 Mar 30 14:41 .
drwx------  4 root root   4096 Mar 30 14:41 ..
drwxr-xr-x  2 root root   4096 Mar 30 14:41 csi
drwxr-xr-x  3 root root   4096 Mar 30 14:41 etc
drwxrwsr-x  3 root user   4096 Mar 30 14:41 pvc-25b7ac65-1d6d-4020-a53d-e1fbfb102a70
drwxrwsr-x  3 root user   4096 Mar 30 14:41 pvc-6f65bf45-b5b6-4441-8aff-442409c856d1
drwxr-xr-x  4 root root   4096 Mar 30 14:41 run
drwxr-xr-x  3 root root   4096 Mar 30 14:41 sys
drwxrwxrwt  2 root root   4096 Mar 30 14:41 tmp
drwxr-xr-x  4 root root   4096 Dec 14 17:28 var
```

The pvc* folders contain everything that should be on the volume.

**Comment by Praveenrajmani** [comment]
Need to investigate this, directpv doesn't do volume snapshots. Can you confirm if these PVCs were provisioned by directpv?

**Comment by WolfspiritM** [comment]
@Praveenrajmani 

```
> kubectl get pvc
NAME                                                    STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS        AGE
...
data0-minio-ss-0-2                                      Bound    pvc-25b7ac65-1d6d-4020-a53d-e1fbfb102a70   49Gi       RWO            direct-csi-min-io   64d
data1-minio-ss-0-2                                      Bound    pvc-6f65bf45-b5b6-4441-8aff-442409c856d1   49Gi       RWO            direct-csi-min-io   64d
...
```

It all started with a reboot of the workers. I didn't notice it before.

It seems like it has nothing to do with Volume Snapshots but with containerd's overlayfs snapshot. The directory I've posted above looks like the directory of the "direct-csi" container of the deamonset. There even was a driver-termination-log in the /var/log folder.

Does the direct-csi container have folders or mounts for each pvc it mounted in the root? It of some reason it seems like out of some reason these are getting picked up by the overlayfs snapshot as if it's not a mount but a container volume.

After restarting the kubelet it cleaned up the snapshot and so far it seems like it hasn't created them again.
At least not with all the files. It went from 100% inode usage to 14%. I have had this happen with 2 of 4 workers.

This happened with 2.0.2. I've now updated to 2.0.9 maybe that fixed it?

**Comment by Praveenrajmani** [comment]
>  I've now updated to 2.0.9 maybe that fixed it?

yes, there were some bug fixes made to handle node restarts correctly in the latest versions. Please use v2.0.9 (latest) and make a note that `--dynamic-discovery` flag during install is still experimental and not ready yet.

you can try without `--dynamic-discovery` in the install command

> Like if the files were created in the container and not on the mount

you can verify this by exec-ing into the workload pod and see if the volumes are mounted on drives and not on root. 

`kubectl exec -it <pod> -- sh` and `df -h` inside the pod can tell if the volumes for the pod are mounted on the drives or root

**Comment by Praveenrajmani** [comment]
I'm closing this issue for now as the issue with node reboots are fixed in the latest versions. Please use the latest version and if you still see the problems. Please re-open this issue.
