### ISSUE TITLE
consider using krew-release-bot for automated krew releases

### ISSUE THREAD

**Issue by rajatjindal** [minio/directpv#570]
Hi Team,

would you please consider using [krew-release-bot](https://github.com/rajatjindal/krew-release-bot) for automated krew plugin releases. 

(disclaimer: I am author of krew-release-bot).

a sample PR opened by the bot can be seen here: https://github.com/kubernetes-sigs/krew-index/pull/2157

many thanks for consideration.

Thanks
Rajat Jindal

**Comment by Praveenrajmani** [comment]
this is a follow-up of https://github.com/minio/directpv/issues/453

**Comment by harshavardhana** [comment]
We will not be doing this, since we have some internal requirements to meet before we publish binaries.  Building it on GitHub infrastructure is a risk - our binaries are built privately. 

We will look at doing this via GitHub runners in future.
