### ISSUE TITLE
[Question] Invalid Argument when using format command

### ISSUE THREAD

**Issue by hhuangpen** [minio/directpv#573]
When I format and mount the external drive, it fails to mount the drive with invalid argument. 
<img width="699" alt="Screen Shot 2022-04-14 at 7 39 47 PM" src="https://user-images.githubusercontent.com/82373357/163383607-ed617031-1f13-49a6-9c12-3bad2b9c5f11.png">
 
Here is the log:
<img width="1590" alt="Screen Shot 2022-04-14 at 4 38 37 PM" src="https://user-images.githubusercontent.com/82373357/163383672-6182e23b-ef1a-47df-85bb-af6331e59b51.png">

Is there any way to gather the information of the options and arguments passing in?

**Comment by Praveenrajmani** [comment]
looks like mount is failing @hhuangpen can you check the `dmesg` to see if there are any mount related errors? Additionally, can you check the directpv version and the OS that is being used here? 

also, get the corresponding drive yaml - `kubectl directpv drives list --drives /dev/<name> --nodes <node_name> -o yaml`

**Comment by Praveenrajmani** [comment]
also, was there a kernel upgrade? what is the current kernel version being used?

**Comment by hhuangpen** [comment]
@Praveenrajmani Thanks for the quick answer. I am using siderolabs/Talos Linux. Its release is 1.0.0 and I believe its kernel version is 5.15.32. Here are the outputs of **dmseg** and it seems quota is not available:
<img width="1623" alt="Screen Shot 2022-04-15 at 9 07 01 AM" src="https://user-images.githubusercontent.com/82373357/163502456-32acba8f-cdc9-4a9f-b31b-f1339639a94b.png">

Output of **list** command:
<img width="475" alt="Screen Shot 2022-04-15 at 9 09 28 AM" src="https://user-images.githubusercontent.com/82373357/163502457-3074d22d-0597-4988-bdc6-cbdd44f4b283.png">

**Comment by Praveenrajmani** [comment]
can you paste the output of `lsblk`?

**Comment by Praveenrajmani** [comment]
> Here are the outputs of dmseg and it seems quota is not available:

yeah, looks like a siderolabs/Talos Linux uses a customized kernel build with [kernel self protection project](https://kernsec.org/wiki/index.php/Kernel_Self_Protection_Project) where `prjquota` is not supported.

directpv requires xfs_quota to set volume limits and read volume stats

**Comment by hhuangpen** [comment]
I see. I'll inform talos linux for this. Since Talos is prohibited using ssh and only can access each nodes through talos cli, its counterpart output is something like this:
<img width="1287" alt="Screen Shot 2022-04-15 at 6 33 28 PM" src="https://user-images.githubusercontent.com/82373357/163561268-630aeecf-a5db-4894-b729-576fc1bf4a8b.png">
