### ISSUE TITLE
livenessprobe and csi-node-driver-registrar lack arm64 support

### ISSUE THREAD

**Issue by htr** [minio/directpv#592]
the images `quay.io/minio/livenessprobe` and `quay.io/minio/csi-node-driver-registrar` fail to start in my arm64 with the following error:

```
standard_init_linux.go:228: exec user process caused: exec format error
``` 

comparing the output of `docker manifest inspect quay.io/minio/csi-node-driver-registrar:v2.2.0-go1.18` 
with `docker manifest inspect quay.io/minio/directpv:v3.0.1` shows the lack of arm64 support in both livenessprobe and csi-node-driver-registrar images.

**Comment by harshavardhana** [comment]
We never built arm64 image for them

**Comment by neulchance** [comment]
@harshavardhana 

-- Environment --
Hardware: Raspberry pi 4
OS: Ubuntu 20.04.2 LTS (GNU/Linux 5.4.0-1059-raspi aarch64)
Kubernetes Version: K3S v1.20

-- Question --
While installing on above environment using command `kubectl directpv install`.
I can't install. Above environment does not worth a try to install?
I expected to install with no special action for succeed install. I need advice.

**Comment by htr** [comment]
> We never built arm64 image for them

Are there any differences between `quay.io/minio/csi-node-driver-registrar` and `sig-storage/csi-node-driver-registrar` ?

And between `minio/livenessprobe` and `sig-storage/livenessprobe` ?

the sig-storage/* images support arm64.

**Comment by harshavardhana** [comment]
Mainly because we had to recompile them to fix some Go runtime vulnerabilities. 

I shall let @Praveenrajmani why was it decided to use a non upstream build.

**Comment by Praveenrajmani** [comment]
> And between minio/livenessprobe and sig-storage/livenessprobe ?

There is no any difference, as @harshavardhana explained, we had to recompile it with latest go to fix some vulnerabilities. You can also use the upstream image by editing and applying the yaml generated by `kubectl directpv install --dry-run`.

The latest side-car versions used are,

```
csi-provisioner:v2.2.0
csi-node-driver-registrar:v2.2.0
livenessprobe:v2.2.0
```
