### ISSUE TITLE
after deleting tenant and all its pvc drives are showing inuse and not able install new tenant

### ISSUE THREAD

**Issue by mukhtar-inamdar** [minio/directpv#607]
**Describe the bug**
after deleting the tenant and all its PVC drives are showing inuse and not able to install a new tenant

**To Reproduce**
create a kerbernetes setup, install krew.
install directpv and init
install minio operator
create a tenant
check all running well all pods are online and all pv are bound with PVC.
do some io operation
then delete tenant 'kubectl minio tenant delete <tenant1>'
then delete PVCs 'kubectl delete pvc -n <tenant-namespace> --all'
check if all pvc and pv get deleted
then delete namespace 'kubectl delete namespace <tenant-namespace>'
wait for some time then check 'kubectl directpv drives list' showing drives status inuse

**Expected behavior**
drives should be back in ready state

**Screenshots and logs**
![image](https://user-images.githubusercontent.com/93313283/176130328-5999d02b-7262-42c3-a830-2b76706dd102.png)

![image](https://user-images.githubusercontent.com/93313283/176130667-e84d501c-245b-4319-8de5-6b0100a9d522.png)

*Showing no volumes*
![image](https://user-images.githubusercontent.com/93313283/176131080-0f2e966c-fbac-4ddb-82a8-6cfa7df07ccb.png)

If applicable, add screenshots to help explain your problem. Or logs from the pods in direct-csi-min-io namespace. 

[direct-csi-min-io.log.zip](https://github.com/minio/directpv/files/8999236/direct-csi-min-io.log.zip)

**Deployment information (please complete the following information):**
 - DirectPV version: (This can be captured by `kubectl directpv --version`) directpv version v3.0.2
 - Kubernetes Version:
 ```
 [root@ssc-vm-rhev4-2678 ~]# kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.6", GitCommit:"f59f5c2fda36e4036b49ec027e556a15456108f0", GitTreeState:"clean", BuildDate:"2022-01-19T17:33:06Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.9", GitCommit:"6df4433e288edc9c40c2e344eb336f63fad45cd2", GitTreeState:"clean", BuildDate:"2022-04-13T19:52:02Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
```
 - OS info: Red Hat 3.10.0-1160.el7.x86_64
- Kernel version: Linux version 3.10.0-1160.el7.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC) ) #1 SMP Mon Oct 19 16:18:59 UTC 2020

**Additional context**

**Comment by Praveenrajmani** [comment]
you can purge the stale volumes by `kubectl directpv volumes purge --all` @mukhtar-inamdar

**Comment by mukhtar-inamdar** [comment]
@Praveenrajmani 
> you can purge the stale volumes by `kubectl directpv volumes purge --all` @mukhtar-inamdar

no volumes are listed I have uploaded the image for same.

**Comment by Praveenrajmani** [comment]
> kubectl directpv volumes purge --all

this command will not print anything, it will just purge the stale volumes @mukhtar-inamdar

**Comment by mukhtar-inamdar** [comment]
> kubectl directpv volumes purge --all

Hi @Praveenrajmani,
I am not talking about the purge command I run list command and it is not listing any volume as there is no volume after deleing all tenant PVCs I have mentioned in above steps
![image](https://user-images.githubusercontent.com/93313283/176147499-1862ae19-a9b4-423c-8603-211b9609ebfa.png)

**Comment by Praveenrajmani** [comment]
`kubectl directpv volumes list --all` will show the unpublished volumes. Without `--all` it will just display the published volumes @mukhtar-inamdar

**Comment by mukhtar-inamdar** [comment]
> `kubectl directpv volumes list --all` will show the unpublished volumes. Without `--all` it will just display the published volumes @mukhtar-inamdar

Oh, OK!
Thanks.
I have recreated a setup and will check it in sometime.

**Comment by Praveenrajmani** [comment]
one more small thing is required, can you do `kubectl directpv drives list --all --drives /dev/dm-1,/dev/sr1 -o yaml > /tmp/drives.yaml` and paste the output here @mukhtar-inamdar

**Comment by mukhtar-inamdar** [comment]
[dev_dm.zip](https://github.com/minio/directpv/files/9000005/dev_dm.zip)
But this is from a fresh setup and not with above issue.

**Comment by Praveenrajmani** [comment]
Thanks. also, the output of `cat /run/udev/data/b253:1` and `cat /run/udev/data/b11:1` from any one of the worker node @mukhtar-inamdar

**Comment by mukhtar-inamdar** [comment]
[udev_data_bxx.txt](https://github.com/minio/directpv/files/9000088/udev_data_bxx.txt)

**Comment by Praveenrajmani** [comment]
thanks @mukhtar-inamdar . Just wanted to understand few things about these drives `/dev/dm-1` and `/dev/sr1`. 

Can you paste the output of `udevadm monitor --udev  --subsystem-match=block`?

**Comment by Praveenrajmani** [comment]
Are these swap drives?

**Comment by Praveenrajmani** [comment]
Figured it out by looking into the udev data file shared. Thanks!

Closing this issue, please feel free to re-open if you see any issues.
