### ISSUE TITLE
Problem to format disks sata

### ISSUE THREAD

**Issue by lesomora** [minio/directpv#608]
When I try format using -f or --force option, I got this message: 

[_lsouza@drax01][fluentd-kubernetes-daemonset]$ kubectl-directpv drives list --nodes=minio0006 
 DRIVE     CAPACITY  ALLOCATED  FILESYSTEM  VOLUMES  NODE       ACCESS-TIER  STATUS                                                                                                                                                              
 /dev/sda  7.3 TiB   -          -           -        minio0006  -            Available*  unable to execute command [mkfs.xfs -i maxpct=50 -m uuid= -L DIRECTCSI /dev/sda]; output=mkfs.xfs: /dev/sda appears to contain a partition table (gpt). 
 /dev/sdb  7.3 TiB   -          -           -        minio0006  -            Available*  unable to execute command [mkfs.xfs -i maxpct=50 -m uuid= -L DIRECTCSI /dev/sdb]; output=mkfs.xfs: /dev/sdb appears to contain a partition table (gpt). 
 /dev/sdc  7.3 TiB   -          -           -        minio0006  -            Available*  unable to execute command [mkfs.xfs -i maxpct=50 -m uuid= -L DIRECTCSI /dev/sdc]; output=mkfs.xfs: /dev/sdc appears to contain a partition table (gpt). 
 /dev/sdd  7.3 TiB   -          -           -        minio0006  -            Available*  unable to execute command [mkfs.xfs -i maxpct=50 -m uuid= -L DIRECTCSI /dev/sdd]; output=mkfs.xfs: /dev/sdd appears to contain a partition table (gpt). 
 /dev/sde  1.7 TiB   -          xfs         -        minio0006  -            Ready                                                                                                                                                               
 /dev/sdf  1.7 TiB   -          xfs         -        minio0006  -            Ready                                                                                                                                                               
 /dev/sdg  7.3 TiB   -          -           -        minio0006  -            Available*  unable to execute command [mkfs.xfs -i maxpct=50 -m uuid= -L DIRECTCSI /dev/sdg]; output=mkfs.xfs: /dev/sdg appears to contain a partition table (gpt). 
 /dev/sdh  7.3 TiB   -          -           -        minio0006  -            Available*  unable to execute command [mkfs.xfs -i maxpct=50 -m uuid= -L DIRECTCSI /dev/sdh]; output=mkfs.xfs: /dev/sdh appears to contain a partition table (gpt). 
 /dev/sdi  7.3 TiB   -          -           -        minio0006  -            Available*  unable to execute command [mkfs.xfs -i maxpct=50 -m uuid= -L DIRECTCSI /dev/sdi]; output=mkfs.xfs: /dev/sdi appears to contain a partition table (gpt). 
 /dev/sdj  7.3 TiB   -          -           -        minio0006  -            Available*  unable to execute command [mkfs.xfs -i maxpct=50 -m uuid= -L DIRECTCSI /dev/sdj]; output=mkfs.xfs: /dev/sdj appears to contain a partition table (gpt). 
 /dev/sdk  7.3 TiB   -          -           -        minio0006  -            Available*  unable to execute command [mkfs.xfs -i maxpct=50 -m uuid= -L DIRECTCSI /dev/sdk]; output=mkfs.xfs: /dev/sdk appears to contain a partition table (gpt). 
 /dev/sdl  7.3 TiB   -          -           -        minio0006  -            Available*  unable to execute command [mkfs.xfs -i maxpct=50 -m uuid= -L DIRECTCSI /dev/sdl]; output=mkfs.xfs: /dev/sdl appears to contain a partition table (gpt). 
 /dev/sdm  7.3 TiB   -          -           -        minio0006  -            Available*  unable to execute command [mkfs.xfs -i maxpct=50 -m uuid= -L DIRECTCSI /dev/sdm]; output=mkfs.xfs: /dev/sdm appears to contain a partition table (gpt). 
 /dev/sdn  7.3 TiB   -          -           -        minio0006  -            Available*  unable to execute command [mkfs.xfs -i maxpct=50 -m uuid= -L DIRECTCSI /dev/sdn]; output=mkfs.xfs: /dev/sdn appears to contain a partition table (gpt). 
 /dev/sdo  7.3 TiB   -          -           -        minio0006  -            Available*  unable to execute command [mkfs.xfs -i maxpct=50 -m uuid= -L DIRECTCSI /dev/sdo]; output=mkfs.xfs: /dev/sdo appears to contain a partition table (gpt). 
 /dev/sdp  7.3 TiB   -          -           -        minio0006  -            Available*  unable to execute command [mkfs.xfs -i maxpct=50 -m uuid= -L DIRECTCSI /dev/sdp]; output=mkfs.xfs: /dev/sdp appears to contain a partition table (gpt). 
 /dev/sdq  7.3 TiB   -          -           -        minio0006  -            Available*  unable to execute command [mkfs.xfs -i maxpct=50 -m uuid= -L DIRECTCSI /dev/sdq]; output=mkfs.xfs: /dev/sdq appears to contain a partition table (gpt). 
 /dev/sdr  7.3 TiB   -          -           -        minio0006  -            Available*  unable to execute command [mkfs.xfs -i maxpct=50 -m uuid= -L DIRECTCSI /dev/sdr]; output=mkfs.xfs: /dev/sdr appears to contain a partition table (gpt).

I've try format manually and the command running fine: 

Model: DELL PERC H740P Mini (scsi)
Disk /dev/sda: 8001GB
Sector size (logical/physical): 512B/512B
Partition Table: loop
Disk Flags: 

Number  Start  End     Size    File system  Flags
 1      0.00B  8001GB  8001GB  xfs

I can mount the disk on /mnt 

/dev/sda        7.3T   52G  7.3T   1% /mnt

But when I tried format using direct-pv only my ssd's works fine. 

I've more 6 nodes with the same setup and works fine

**Comment by harshavardhana** [comment]
you cannot have existing partitioned drives @lesomora 

> Model: DELL PERC H740P Mini (scsi)
> Disk /dev/sda: 8001GB
> Sector size (logical/physical): 512B/512B
> Partition Table: loop
> Disk Flags:

Please remove your RAID Controller we do not recommend that you use logical volumes here.

**Comment by lesomora** [comment]
So the best pratice is use JBOD or something like that  ? 

I will try

**Comment by harshavardhana** [comment]
> So the best pratice is use JBOD or something like that ?

Yes JBOD is the way to go for best performance.

**Comment by Praveenrajmani** [comment]
As explained, You cannot use stale gpt partitioned disks. Looks like the disks had gpt partitions earlier and are not cleaned up properly. 

You can use JBODs instead.
