### ISSUE TITLE
kubectl-directpv volumes list showup volumes doest exist

### ISSUE THREAD

**Issue by lesomora** [minio/directpv#611]
I did a first deployment with size 1TB, now I need to do same in production enviroment. 

That's my config: 

kubectl-directpv info 
 NODE         CAPACITY  ALLOCATED  VOLUMES  DRIVES 
 • minio0001  116 TiB   0 B        0        16     
 • minio0002  116 TiB   0 B        0        16     
 • minio0003  116 TiB   0 B        0        16     
 • minio0004  116 TiB   0 B        0        16     
 • minio0005  116 TiB   0 B        0        16     
 • minio0006  116 TiB   0 B        0        16     
 • minio0007  116 TiB   0 B        0        16     

0 B/815 TiB used, 159 volumes, 112 drives

I'm using 0B of 815TB but is show up to me 159 volumes. When I tried to list thoose volumes, I got this empty output: 

kubectl-directpv volumes list
 VOLUME  CAPACITY  NODE  DRIVE  PODNAME  PODNAMESPACE
 
 I just checked the scheduler events, I got this message: 
 
   Warning  FailedScheduling  4m12s                  default-scheduler  running PreBind plugin "VolumeBinding": binding volumes: provisioning failed for PVC "data11-storage-pool-0-0"
  Warning  FailedScheduling  4m10s                  default-scheduler  0/10 nodes are available: 2 Insufficient memory, 3 Insufficient cpu, 3 node(s) had taint {node-role.kubernetes.io/master: }, that the pod didn't tolerate, 4 node(s) had volume node affinity conflict.
  Warning  FailedScheduling  4m                     default-scheduler  running PreBind plugin "VolumeBinding": binding volumes: provisioning failed for PVC "data11-storage-pool-0-0"
  Warning  FailedScheduling  3m36s (x1 over 3m50s)  default-scheduler  running PreBind plugin "VolumeBinding": binding volumes: provisioning failed for PVC "data11-storage-pool-0-0"
  Warning  FailedScheduling  26s                    default-scheduler  running PreBind plugin "VolumeBinding": binding volumes: provisioning failed for PVC "data11-storage-pool-0-0"
  Warning  FailedScheduling  2s (x1 over 13s)       default-scheduler  running PreBind plugin "VolumeBinding": binding volumes: provisioning failed for PVC "data11-storage-pool-0-0"

I checked my nodes and I've CPU, Memory e Disk to allocate: 

NAME        CPU(cores)   CPU%   MEMORY(bytes)   MEMORY%   
cpstr01     384m         19%    5171Mi          65%       
cpstr02     403m         20%    4477Mi          56%       
cpstr03     1645m        41%    4988Mi          63%       
minio0001   156m         1%     2010Mi          3%        
minio0002   203m         1%     2795Mi          4%        
minio0003   135m         1%     4756Mi          7%        
minio0004   153m         1%     2971Mi          4%        
minio0005   1117m        9%     4526Mi          7%        
minio0006   134m         1%     2188Mi          3%        
minio0007   145m         1%     2515Mi          3%   

I dont know where I missed some configuration. I checked my configuration on console. I did that: 

![Captura de Tela_Área de Seleção_20220713195056](https://user-images.githubusercontent.com/51002411/178850303-79a45f15-592f-4523-a027-2866fbd24d74.png)

Can you help me ?

**Comment by Praveenrajmani** [comment]
you need to purge the deleted volumes using `kubectl directpv volumes purge --all` 

make sure, the corresponding PVCs are deleted before executing the purge command.

`kubectl directpv volumes list --all` will list the stale un-purged volumes as well.
