### ISSUE TITLE
run `kubectl directpv install` on windows creates yaml file with image name with `\` (should be `/`), results in install failure

### ISSUE THREAD

**Issue by nasusoba** [minio/directpv#617]
**Describe the bug**
I run kubectl on my windows machine, targeting a linux kubernetes cluster. The image name generated is like `quay.io\minio\directpv`, which should be `quay.io/minio/directpv`, results in container creation failure

**To Reproduce**
On windows machine, run `kubectl directpv install`

**Log**
```
Warning  InspectFailed  7s (x4 over 33s)  kubelet            Failed to apply default image tag "quay.io\\minio\\csi-provisioner@sha256:c185db49ba02c384633165894147f8d7041b34b173e82a49d7145e50e809b8d6": couldn't parse image reference "quay.io\\minio\\csi-provisioner@sha256:c185db49ba02c384633165894147f8d7041b34b173e82a49d7145e50e809b8d6": invalid reference format
```

**Expected behavior**
Image name should be `quay.io/minio/directpv`

**Suggestion**
I check the code, seems that [filepath.Join](https://github.com/minio/directpv/blob/master/pkg/installer/deployment.go#:~:text=Image%3A%20filepath.Join(c.DirectCSIContainerRegistry%2C%20c.DirectCSIContainerOrg%2C%20c.getCSIProvisionerImage())%2C) is used, which results in this issue. Should we just hardcode with `/` ?

**Comment by harshavardhana** [comment]
> **Describe the bug** I run kubectl on my windows machine, targeting a linux kubernetes cluster. The image name generated is like `quay.io\minio\directpv`, which should be `quay.io/minio/directpv`, results in container creation failure
> 
> **To Reproduce** On windows machine, run `kubectl directpv install`
> 
> **Log**
> 
> ```
> Warning  InspectFailed  7s (x4 over 33s)  kubelet            Failed to apply default image tag "quay.io\\minio\\csi-provisioner@sha256:c185db49ba02c384633165894147f8d7041b34b173e82a49d7145e50e809b8d6": couldn't parse image reference "quay.io\\minio\\csi-provisioner@sha256:c185db49ba02c384633165894147f8d7041b34b173e82a49d7145e50e809b8d6": invalid reference format
> ```
> 
> **Expected behavior** Image name should be `quay.io/minio/directpv`
> 
> **Suggestion** I check the code, seems that [filepath.Join](https://github.com/minio/directpv/blob/master/pkg/installer/deployment.go#:~:text=Image%3A%20filepath.Join(c.DirectCSIContainerRegistry%2C%20c.DirectCSIContainerOrg%2C%20c.getCSIProvisionerImage())%2C) is used, which results in this issue. Should we just hardcode with `/` ?

Instead of filepath.Join we should use path.Join @Praveenrajmani

**Comment by harshavardhana** [comment]
This PR should fix the issue here https://github.com/minio/directpv/pull/618

**Comment by Praveenrajmani** [comment]
The PR got merged
