### ISSUE TITLE
[Feature request] Volume expansion is not currently available, are there any plans to implement it?

### ISSUE THREAD

**Issue by guanxingfeng** [minio/directpv#630]
**Describe the bug**
I found Volume expansion is not currently available, are there any plans to implement it?and when？

**To Reproduce**

**Expected behavior**

**Screenshots and logs**

![image](https://user-images.githubusercontent.com/25924966/188065841-fb95d28e-3c3d-4fe8-b3d0-78683614feeb.png)
![image](https://user-images.githubusercontent.com/25924966/188066030-5b831918-0c5d-4156-a79e-e6790f411aa1.png)

**Deployment information (please complete the following information):**
 - DirectPV version: (This can be captured by `kubectl directpv --version`)
 - Kubernetes Version:
 - OS info:
- Kernel version:

**Additional context**

**Comment by Praveenrajmani** [comment]
Thanks for filing @guanxingfeng, Yes - volume expansion is not supported yet.

will discuss this internally and let you know.

**Comment by Daxcor69** [comment]
Has there been any movement on this issue?  Any decisions made?  I need to make some decisions on my storage.. and expansion is needed.

thanks

**Comment by Praveenrajmani** [comment]
> Has there been any movement on this issue? Any decisions made? I need to make some decisions on my storage.. and expansion is needed.

We will be implementing this soon

**Comment by Praveenrajmani** [comment]
Fixed in https://github.com/minio/directpv/pull/723
