### ISSUE TITLE
[Question] What is the difference between direct-csi-min-io and directpv-min-io storage classes?

### ISSUE THREAD

**Issue by chenliu1993** [minio/directpv#634]
As title. I install directpv through `krew`. but I cannot figure it out the difference between these two storageclasses.
Can someone give me a hint?

**Comment by balamurugana** [comment]
We are working on moving all reference from `directcsi` to `directpv`. Stay tuned!

**Comment by Praveenrajmani** [comment]
Any one of them can be used for now @chenliu1993 

bot `directpv-min-io` and `direct-csi-min-io` storage class name will work. Both are same. The older - `direct-csi-min-io` is maintained for backward compatibility
