### ISSUE TITLE
Readiness probe failed with 404 for direct-csi container

### ISSUE THREAD

**Issue by ondrej-smola** [minio/directpv#635]
**Describe the bug**
Seems like readiness probe is badly configured for direct-csi pod

**To Reproduce**
Perform basic installation

**Expected behavior**
Readiness check should pass

**Screenshots and logs**

![readiness_check_failed](https://user-images.githubusercontent.com/851390/189637040-1ef5b79f-d306-45fa-8438-113e4ec1ea82.jpg)

**Deployment information (please complete the following information):**
 - DirectPV version: 3.0.4
 - Kubernetes Version: 1.23.9
 - OS info: Ubuntu 20.04

**Additional context**
Working when readiness check removed

**Comment by Praveenrajmani** [comment]
Readiness checks are re-implemented in https://github.com/minio/directpv/pull/621

The next release should have these changes.

**Comment by ondrej-smola** [comment]
Thank you - missed that
