### ISSUE TITLE
Failed to provision volume with StorageClass "direct-csi-min-io": rpc error: code = ResourceExhausted desc = no drive found for requested topology

### ISSUE THREAD

**Issue by ondrej-smola** [minio/directpv#637]
**Describe the bug**
When testing minio direct-pv for database deployment (e.g. etcd) not all persistent volume claims are bound.

`Failed to provision volume with StorageClass "directpv-min-io": rpc error: code = ResourceExhausted desc = no drive found for requested topology`

**To Reproduce**

1. Install directpv
2. setup 3+ drives
3. `helm install --set "replicaCount=3" --set "global.storageClass=direct-csi-min-io"  my-release bitnami/etcd`

**Expected behavior**
All PVCs should be bound when there is enough space

**Screenshots and logs**
![pvcs](https://user-images.githubusercontent.com/851390/189641246-fb1fc61d-fda1-4d18-9667-1c4dafcc58cb.jpg)
![cli](https://user-images.githubusercontent.com/851390/189641406-9289f649-c409-4b25-a9f6-b344e0b52b3c.jpg)

**Deployment information (please complete the following information):**
 - DirectPV version: 3.0.4
 - Kubernetes Version: 1.23.9
 - OS info: ubuntu 20.04

**Additional context**
Provisioning same resource using Ceph storage or local volume works

**Comment by Praveenrajmani** [comment]
looks like the pods are deployed on a node where no ready drives are present @ondrej-smola 

you can have necessary node selectors to deploy pods on the correct nodes.

**Comment by ondrej-smola** [comment]
@Praveenrajmani thank you for really quick response ... i have same problem when deploying only 2 replicas ... also tried with PostgreSQL operator

**Comment by Praveenrajmani** [comment]
Can you check on which nodes these pods are scheduled @ondrej-smola ?

`kubectl get pods -n <ns> -o wide` can tell you this

**Comment by ondrej-smola** [comment]
same command just 2 replicas
`helm install --set "replicaCount=2" --set "global.storageClass=direct-csi-min-io"  my-release bitnami/etcd`

result 
```
 DRIVE           CAPACITY  ALLOCATED  FILESYSTEM      VOLUMES  NODE     ACCESS-TIER  STATUS
 /dev/nvme1n1p2  48 GiB    -          -               -        node-10  -            Available
 /dev/nvme1n1p2  48 GiB    -          -               -        node-11  -            Available
 /dev/nvme0n1p3  699 GiB   -          ceph_bluestore  -        node-12  -            Available
 /dev/nvme0n1p3  699 GiB   13 GiB     xfs             1        node-13  -            InUse
 /dev/nvme0n1p3  699 GiB   -          xfs             -        node-14  -            Ready
 /dev/nvme1n1p2  48 GiB    -          -               -        node-15  -            Available
 /dev/sda3       699 GiB   -          xfs             -        node-16  -            Ready
```
it seems like the last one just does not get scheduled

```
NAME                READY   STATUS    RESTARTS      AGE    IP            NODE      NOMINATED NODE   READINESS GATES
my-release-etcd-0   0/1     Running   1 (48s ago)   110s   10.0.10.234   node-13   <none>           <none>
my-release-etcd-1   0/1     Pending   0             110s   <none>        <none>    <none>           <none>

```

**Comment by ondrej-smola** [comment]
```
Name:          data-my-release-etcd-1
Namespace:     postgres-test
StorageClass:  direct-csi-min-io
Status:        Pending
Volume:        
Labels:        app.kubernetes.io/instance=my-release
               app.kubernetes.io/name=etcd
Annotations:   volume.beta.kubernetes.io/storage-provisioner: direct-csi-min-io
               volume.kubernetes.io/storage-provisioner: direct-csi-min-io
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      
Access Modes:  
VolumeMode:    Filesystem
Used By:       my-release-etcd-1
Events:
  Type     Reason                Age                     From                                                                                       Message
  ----     ------                ----                    ----                                                                                       -------
  Normal   WaitForFirstConsumer  3m44s                   persistentvolume-controller                                                                waiting for first consumer to be created before binding
  Normal   ExternalProvisioning  2m33s (x10 over 3m44s)  persistentvolume-controller                                                                waiting for a volume to be created, either by external provisioner "direct-csi-min-io" or manually created by system administrator
  Normal   WaitForPodScheduled   2m33s (x14 over 3m44s)  persistentvolume-controller                                                                waiting for pod my-release-etcd-1 to be scheduled
  Warning  ProvisioningFailed    117s (x12 over 3m44s)   direct-csi-min-io_direct-csi-min-io-7768bf55b4-4455n_3e6804f8-71c6-450c-a110-f3d090c7facd  failed to provision volume with StorageClass "direct-csi-min-io": rpc error: code = ResourceExhausted desc = no drive found for requested topology
  Normal   Provisioning          105s (x13 over 3m44s)   direct-csi-min-io_direct-csi-min-io-7768bf55b4-4455n_3e6804f8-71c6-450c-a110-f3d090c7facd  External provisioner is provisioning volume for claim "postgres-test/data-my-release-etcd-1"
```

**Comment by Praveenrajmani** [comment]
mostly looks like the pod is asking for volumes where directpv is not installed or do not have any ready drives @ondrej-smola 

Can you edit the direct-csi-min-io deployment - `kubectl edit deployment direct-csi-min-io -n direct-csi-min-io` and change the verbosity of the `direct-csi` container from `-v=3` to `-v=5`?

**Comment by Praveenrajmani** [comment]
and get us the logs from the deployment pods

**Comment by ondrej-smola** [comment]
```
I0912 11:44:27.623316       1 controller.go:1332] provision "postgres-test/data-my-release-etcd-1" class "direct-csi-min-io": started
W0912 11:44:27.623378       1 controller.go:571] "fstype" is deprecated and will be removed in a future release, please use "csi.storage.k8s.io/fstype" instead
I0912 11:44:27.623412       1 connection.go:182] GRPC call: /csi.v1.Controller/CreateVolume
I0912 11:44:27.623484       1 event.go:282] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"postgres-test", Name:"data-my-release-etcd-1", UID:"4343711e-9155-4d47-aa2b-6e45b08b74d0", APIVersion:"v1", ResourceVersion:"56911791", FieldPath:""}): type: 'Normal' reason: 'Provisioning' External provisioner is provisioning volume for claim "postgres-test/data-my-release-etcd-1"
I0912 11:44:27.623417       1 connection.go:183] GRPC request: {"accessibility_requirements":{"preferred":[{"segments":{"direct.csi.min.io/identity":"direct-csi-min-io","direct.csi.min.io/node":"node-12","direct.csi.min.io/rack":"default","direct.csi.min.io/region":"default","direct.csi.min.io/zone":"default"}}],"requisite":[{"segments":{"direct.csi.min.io/identity":"direct-csi-min-io","direct.csi.min.io/node":"node-12","direct.csi.min.io/rack":"default","direct.csi.min.io/region":"default","direct.csi.min.io/zone":"default"}}]},"capacity_range":{"required_bytes":8589934592},"name":"pvc-4343711e-9155-4d47-aa2b-6e45b08b74d0","parameters":{"fstype":"xfs"},"volume_capabilities":[{"AccessType":{"Mount":{"fs_type":"xfs"}},"access_mode":{"mode":1}}]}
I0912 11:44:27.790180       1 connection.go:185] GRPC response: {}
I0912 11:44:27.790212       1 connection.go:186] GRPC error: rpc error: code = ResourceExhausted desc = no drive found for requested topology
I0912 11:44:27.790227       1 controller.go:753] CreateVolume failed, supports topology = true, node selected true => may reschedule = true => state = Reschedule: rpc error: code = ResourceExhausted desc = no drive found for requested topology
I0912 11:44:27.790337       1 event.go:282] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"postgres-test", Name:"data-my-release-etcd-1", UID:"4343711e-9155-4d47-aa2b-6e45b08b74d0", APIVersion:"v1", ResourceVersion:"56911791", FieldPath:""}): type: 'Warning' reason: 'ProvisioningFailed' failed to provision volume with StorageClass "direct-csi-min-io": rpc error: code = ResourceExhausted desc = no drive found for requested topology
I0912 11:44:27.807549       1 controller.go:1426] provision "postgres-test/data-my-release-etcd-1" class "direct-csi-min-io": volume rescheduled because: failed to provision volume with StorageClass "direct-csi-min-io": rpc error: code = ResourceExhausted desc = no drive found for requested topology
I0912 11:44:27.807723       1 controller.go:1095] Stop provisioning, removing PVC 4343711e-9155-4d47-aa2b-6e45b08b74d0 from claims in progress
I0912 11:44:31.593325       1 leaderelection.go:273] successfully renewed lease direct-csi-min-io/direct-csi-min-io
```

**Comment by ondrej-smola** [comment]
You are right - it is selecting node-12 ... but why?

**Comment by Praveenrajmani** [comment]
no drives are formatted in node-12 @ondrej-smola 

you have to format them to make them `Ready`

**Comment by ondrej-smola** [comment]
@Praveenrajmani  But I dont want to use drive on node-12 ... i though directpv will only use drives I choose and I chose and formatted drives on node node-[13,14,16] ... why is node-12 even considered?

**Comment by ondrej-smola** [comment]
i though that it will ignore available drives when there are ready drives ... i am not selecting node-12 in any way

**Comment by Praveenrajmani** [comment]
DirectPV can't select a node for the pods. It is the k8s that selects nodes. DirectPV will only select drives from the node which was asked by k8s to place the volumes on. 

you can control the node selection for pods by certain ways like node-selectors, node affinity etc. Please refer https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/

**Comment by ondrej-smola** [comment]
@Praveenrajmani that just make sense now - completely missed that :) thank you very much for you explanation

**Comment by Praveenrajmani** [comment]
> I0912 11:44:27.623417       1 connection.go:183] GRPC request: {"accessibility_requirements":{"preferred":[{"segments":{"direct.csi.min.io/identity":"direct-csi-min-io","direct.csi.min.io/node":"node-12","direct.csi.min.io/rack":"default","direct.csi.min.io/region":"default","direct.csi.min.io/zone":"default"}}],"requisite":[{"segments":{"direct.csi.min.io/identity":"direct-csi-min-io","direct.csi.min.io/node":"node-12","direct.csi.min.io/rack":"default","direct.csi.min.io/region":"default","direct.csi.min.io/zone":"default"}}]},"capacity_range":{"required_bytes":8589934592},"name":"pvc-4343711e-9155-4d47-aa2b-6e45b08b74d0","parameters":{"fstype":"xfs"},"volume_capabilities":[{"AccessType":{"Mount":{"fs_type":"xfs"}},"access_mode":{"mode":1}}]}

This is the request sent to directpv to allocate volumes. If you see here 

```
"direct.csi.min.io/node":"node-12"
```

is the node chosen by k8s for this volume.

**Comment by ondrej-smola** [comment]
got it - thank you

**Comment by Praveenrajmani** [comment]
> Just a note, ceph does provide this mechanism to select dedicated node and specific drives.
