### ISSUE TITLE
DirectPV failing on OpenShift 4.11

### ISSUE THREAD

**Issue by kinikiti** [minio/directpv#661]
**Describe the bug**
OKD 4.11 installation on bare metal (EC2).
DirectPV installed.
4 worker nodes with attached EBS volumes.
```
oc directpv info
 NODE              CAPACITY  ALLOCATED  VOLUMES  DRIVES
 • ip-172-16-0-40  50 GiB    0 B        0        1
 • ip-172-16-0-41  50 GiB    0 B        0        1
 • ip-172-16-0-42  50 GiB    0 B        0        1
 • ip-172-16-0-43  50 GiB    0 B        0        1

0 B/198 GiB used, 0 volumes, 4 drives
```
Any attempt to claim volume fails with error messages in the logs:
```
I1024 11:41:07.022441       1 controller.go:1426] provision "tenant/0-minio-tenant-1-ss-0-0" class "direct-csi-min-io": volume rescheduled because: failed to provision volume with StorageClass "direct-csi-min-io": rpc error: code = ResourceExhausted desc = no drive found for requested topology
I1024 11:41:07.022789       1 controller.go:1426] provision "tenant/0-minio-tenant-1-ss-0-2" class "direct-csi-min-io": volume rescheduled because: failed to provision volume with StorageClass "direct-csi-min-io": rpc error: code = ResourceExhausted desc = no drive found for requested topology
I1024 11:41:07.023527       1 controller.go:1426] provision "tenant/0-minio-tenant-1-ss-0-1" class "direct-csi-min-io": volume rescheduled because: failed to provision volume with StorageClass "direct-csi-min-io": rpc error: code = ResourceExhausted desc = no drive found for requested topology
```
Volume state:
```
oc get pv,pvc
NAME                                 STATUS    VOLUME   CAPACITY   ACCESS MODES   STORAGECLASS        AGE
persistentvolumeclaim/csi-pvc        Pending                                      direct-csi-min-io   30m
persistentvolumeclaim/directpv-pvc   Pending                                      directpv-min-io     32m
```
**To Reproduce**
Install fresh OKD
Install fresh DirectPV
Try to claim any volume:
```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-claim
  annotations:
    volume.beta.kubernetes.io/storage-class: "directpv-min-io"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
```
**Expected behavior**
Volume claims

**Deployment information (please complete the following information):**
 - DirectPV version:  `directpv version v3.2.0`
 - Kubernetes Version:
    ```
    kubectl version --short
    Client Version: v1.25.3
    Kustomize Version: v4.5.7
    Server Version: v1.24.0-2566+5157800f2a3bc3-dirty
    ```
 - OS info: `Amazon Linux release 2 (Karoo)`
 - Kernel version: `5.10.135-122.509.amzn2.x86_64`

**Additional context**
We test this setup on vanilla k8s and it works. Fails only with OpenShift.

**Comment by kinikiti** [comment]
Capacity request as you can see is just 1M and drives are 50GiB. Should be ok, no?

Pods are running on every node and cluster is just 4 nodes. But I'll take a look how pods are distributes.
Every node should have every pod?

**Comment by Praveenrajmani** [comment]
Can you confirm if you have only 4 nodes in this cluster? 

If so, we need to investigate the CreateVolume request sent by k8s. The logs will tell us.

Before checking the logs, please set to verbosity >= 5 (v=5)

```
kubectl edit deployment direct-csi-min-io -n direct-csi-min-io
```

and edit the verbosity of direct-csi container.

And check the container logs to see if the request is valid or not.

**Comment by Praveenrajmani** [comment]
Closing this issue, Please feel free to re-open if you see any more issues.
