### ISSUE TITLE
I cannot uninstall a hard disk on a node that is no longer in use

### ISSUE THREAD

**Issue by 1165303548** [minio/directpv#662]
Error message

66323 drives_release.go:108] node03:/dev/sdb in use. Cannot be released

pv and pvc are empty

kubectl get pv -A
No resources found

kubectl get pvc -A
No resources found

But it is marked InUse in directpv available drivers

**Comment by harshavardhana** [comment]
this is because you still have finalizers on this, you must have forcibly deleted things without going through the k8s declarative guidelines.

**Comment by Praveenrajmani** [comment]
you need to purge the directcsivolumes using `kubectl directpv volumes purge` @116530354. `kubectl directpv volumes purge --all` to purge all the deleted volumes
