### ISSUE TITLE
New disk is not available for use in new version of directpv(3.2.1)

### ISSUE THREAD

**Issue by ivanovpavel1983** [minio/directpv#685]
Hello.
We added new disks in virtual machines. Old version of direct-csi can use these disks:
![image](https://user-images.githubusercontent.com/5180093/207803221-c0cbdb22-cdce-46c7-969a-fc1ebfa559df.png)

After that, I updated directpv to the latest version(3.2.1):
![image](https://user-images.githubusercontent.com/5180093/207803646-cc83efcc-812e-429e-8084-1b49cb12d872.png)

Directpv can't find those drives, and when I created logical volume(dm-7) on /dev/sdd, directpv find these disks:
![image](https://user-images.githubusercontent.com/5180093/207804319-ab55cab2-2a80-4c9e-8af0-89095d2c875f.png)

Now is it necessary to create a logical volume or not?

**Comment by Praveenrajmani** [comment]
Firstly,  `v3.2.1` is the latest released version of directpv. And the upgrade steps are defined in https://github.com/minio/directpv#upgrade

And, to see unavailable disks, you need to use `--all` - `kubectl directpv drives list --all`

A disk should match the conditions explained in https://github.com/minio/directpv/blob/master/docs/drive-states.md#available toa make it available.

**Comment by ivanovpavel1983** [comment]
Yes, we use v3.2.1.
And why these disks were available by direct-csi and not available for directpv?
I released LVM
lvchange -an /dev/vg-direct-2/lv-direct-2
lvremove /dev/vg-direct-2/lv-direct-2
vgremove /dev/vg-direct-2
wipefs -a /dev/sdd

![image](https://user-images.githubusercontent.com/5180093/207863787-4aba2ba1-2393-4d34-9c57-814f7282eec9.png)

And run command again:
![image](https://user-images.githubusercontent.com/5180093/207863531-4791572a-c34d-4f94-8539-f697a9aaa218.png)

**Comment by ivanovpavel1983** [comment]
And why swap is avalable for Use?

![image](https://user-images.githubusercontent.com/5180093/207866423-ba85bc05-0da6-4377-89de-60df30204dd0.png)

**Comment by Praveenrajmani** [comment]
the output of `kubectl directpv drives list --all` would list the unavailable drives and the reason why it is not available. 

> And why swap is avalable for Use?

maybe, the swap is off on this device. Check `/proc/swaps` file to know if swap is enabled or not

**Comment by ivanovpavel1983** [comment]
The reason is LVM2_Member. But this disk is not LVM2_Member! I have added information above.

**Comment by Praveenrajmani** [comment]
Can you format the disk once with xfs and then check?

**Comment by ivanovpavel1983** [comment]
Yes of course.
The result is:

![image](https://user-images.githubusercontent.com/5180093/207884325-6fd14a98-dfe1-4c85-980e-bc1071d06016.png)

**Comment by Praveenrajmani** [comment]
ok, looks like the lvm disable doesn't trigger any udev events. DirectPV syncs the device states by listening to udev events.

**Comment by ivanovpavel1983** [comment]
I ran the first commands on a clean device, without LVM

**Comment by Praveenrajmani** [comment]
the device management processes is undertaking a revamp and will be released soon. stay tuned!

**Comment by ivanovpavel1983** [comment]
Great! Thank a lot!
For now, I'll use the workaround with disk formatting and "force" option when will add disk to cluster
Have a nice day!
