### ISSUE TITLE
New drive is not detected.

### ISSUE THREAD

**Issue by parekhcoder** [minio/directpv#692]
I added a new drive on a existing cluster node (Two drives on same node). Directpv detects a one drive but not the newly added drive. Uninstall/Install doesn't help.

kubectl directpv drives ls --all    doesn't show newly added drive.

**Comment by Praveenrajmani** [comment]
Is this a virtual machine @parekhcoder ? And what is the DirectPV version used here?

**Comment by Praveenrajmani** [comment]
Also, paste the output of `kubectl directpv drives list --nodes <nodename> --all` and `lsblk` from that node.

**Comment by parekhcoder** [comment]
Yes Its a virtual machine. directpv version v3.2.0

kubectl directpv drives list --nodes <nodename> --all

 DRIVE     CAPACITY  ALLOCATED  FILESYSTEM  VOLUMES  NODE   ACCESS-TIER  STATUS
 /dev/vdb  1.6 TiB   -          xfs         -        node2  -            Ready

lsblk 

vda                        252:0    0  1.6T  0 disk
├─vda1                     252:1    0    3G  0 part
└─vda2                     252:2    0  1.6T  0 part
vdb                        252:16   0  1.6T  0 disk
└─vdb1                     252:17   0  1.6T  0 part
vdc                        252:32   0  1.6T  0 disk
└─vdc1                     252:33   0  1.6T  0 part

"vdc" is the new drive.

**Comment by Praveenrajmani** [comment]
Looks like, the drives are not attached properly. Ready drives should be mounted on the host. Looks like it is not.

Can you paste the output of `cat /run/udev/data/b252:33`?

**Comment by Praveenrajmani** [comment]
And the logs from ` kubectl logs <pod> -n direct-csi-min-io directpv-drive-discovery`

**Comment by Praveenrajmani** [comment]
The drive discovery mechanism is going through a revamp currently. The next major release will have a different approach to discover the drives. Stay tuned! 

Closing this ticket for now.

**Comment by parekhcoder** [comment]
cat /run/udev/data/b252:33

S:disk/by-path/virtio-pci-0000:00:10.0-part1
S:disk/by-uuid/70338f99-d314-4dc9-ab87-9767fd8be0a8
S:disk/by-path/pci-0000:00:10.0-part1
S:disk/by-partlabel/primary
S:disk/by-partuuid/5d0cb734-0164-473a-bd84-d6ea1dc912f3
I:2402036836403
E:ID_PATH=pci-0000:00:10.0
E:ID_PATH_TAG=pci-0000_00_10_0
E:ID_PART_TABLE_UUID=a6c714f2-ae1f-453c-b22c-bc20dbc276a9
E:ID_PART_TABLE_TYPE=gpt
E:ID_FS_UUID=70338f99-d314-4dc9-ab87-9767fd8be0a8
E:ID_FS_UUID_ENC=70338f99-d314-4dc9-ab87-9767fd8be0a8
E:ID_FS_TYPE=xfs
E:ID_FS_USAGE=filesystem
E:ID_PART_ENTRY_SCHEME=gpt
E:ID_PART_ENTRY_NAME=primary
E:ID_PART_ENTRY_UUID=5d0cb734-0164-473a-bd84-d6ea1dc912f3
E:ID_PART_ENTRY_TYPE=0fc63daf-8483-4772-8e79-3d69d8477de4
E:ID_PART_ENTRY_NUMBER=1
E:ID_PART_ENTRY_OFFSET=2048
E:ID_PART_ENTRY_SIZE=3516325888
E:ID_PART_ENTRY_DISK=252:32
G:systemd
Q:systemd
V:1

**Comment by parekhcoder** [comment]
> The drive discovery mechanism is going through a revamp currently. The next major release will have a different approach to discover the drives. Stay tuned!
> 
> Closing this issue for now.



> And the logs from ` kubectl logs <pod> -n direct-csi-min-io directpv-drive-discovery`

Defaulted container "node-driver-registrar" out of: node-driver-registrar, direct-csi, liveness-probe, directpv-drive-discovery
I1228 07:20:03.269312 1237215 main.go:113] Version: v2.2.0-go1.18
I1228 07:20:03.270040 1237215 main.go:137] Attempting to open a gRPC connection with: "unix:///csi/csi.sock"
I1228 07:20:05.307638 1237215 main.go:144] Calling CSI driver to discover driver name
I1228 07:20:05.311661 1237215 main.go:154] CSI driver name: "direct-csi-min-io"
I1228 07:20:05.312468 1237215 node_register.go:52] Starting Registration Server at: /registration/direct-csi-min-io-reg.sock
I1228 07:20:05.313110 1237215 node_register.go:61] Registration Server started at: /registration/direct-csi-min-io-reg.sock
I1228 07:20:05.313311 1237215 node_register.go:83] Skipping healthz server because HTTP endpoint is set to: ""
I1228 07:20:06.094340 1237215 main.go:80] Received GetInfo call: &InfoRequest{}
I1228 07:20:06.218120 1237215 main.go:90] Received NotifyRegistrationStatus call: &RegistrationStatus{PluginRegistered:true,Error:,}

There is no namespace directpv-drive-discovery

**Comment by parekhcoder** [comment]
@Praveenrajmani I would appreciate if you could reopen the issue.

**Comment by Praveenrajmani** [comment]
> kubectl logs <pod> -n direct-csi-min-io directpv-drive-discovery

**Comment by Praveenrajmani** [comment]
also, the output of `kubectl directpv drives list --all`

**Comment by Praveenrajmani** [comment]
> cat /run/udev/data/b252:33

you can share the udev data output from all the drives from this node. `cat /run/udev/data/b<maj>:<min>` where `maj`, `min` are major and minor number of the drives.

**Comment by balamurugana** [comment]
@parekhcoder The next version of `DirectPV` is under development in [devel branch](https://github.com/minio/directpv/tree/devel) which fixes lots of issues. I have created a snapshot release in own repository. I would strongly recommend to try this.

1. Download DirectPV kubectl plugin for GNU/Linux at https://github.com/balamurugana/directpv/releases/download/v3.1.0-40-gd2dec861/kubectl-directpv
2. Set execute permission like `$ chmod a+x kubectl-directpv`
3. Install DirectPV snapshot by `./kubectl-directpv install --registry docker.io --org baladevel`

If you have any problem feel free to open new issues.

**Comment by parekhcoder** [comment]
> > kubectl logs  -n direct-csi-min-io directpv-drive-discovery
> 
> use `-c` for container name, `kubectl logs <pod> -n direct-csi-min-io -c directpv-drive-discovery`

I1228 13:43:33.276597 1247769 uevent.go:94] "Ready drive corrupted/lost" drive:="/dev/vdb" driveName:="625653c3-41ba-47ba-b8e1-a9515d28b2cc"
I1228 13:43:33.306195 1247769 sync.go:226] error while adding device vdc1: create not allowed while custom resource definition is terminating
I1228 13:43:33.309076 1247769 sync.go:226] error while adding device vdc: create not allowed while custom resource definition is terminating
I1228 13:43:33.311258 1247769 sync.go:226] error while adding device sda: create not allowed while custom resource definition is terminating
I1228 13:43:33.313720 1247769 sync.go:226] error while adding device sda1: create not allowed while custom resource definition is terminating
I1228 13:43:33.316057 1247769 sync.go:226] error while adding device sr0: create not allowed while custom resource definition is terminating
I1228 13:43:33.318494 1247769 sync.go:226] error while adding device sda2: create not allowed while custom resource definition is terminating
I1228 13:43:33.321089 1247769 sync.go:226] error while adding device vda1: create not allowed while custom resource definition is terminating
I1228 13:43:33.323197 1247769 sync.go:226] error while adding device vdb1: create not allowed while custom resource definition is terminating
I1228 13:43:33.325411 1247769 sync.go:226] error while adding device vda2: create not allowed while custom resource definition is terminating
I1228 13:43:33.327477 1247769 sync.go:226] error while adding device vdb: create not allowed while custom resource definition is terminating
I1228 13:43:33.329508 1247769 sync.go:226] error while adding device vda: create not allowed while custom resource definition is terminating

**Comment by parekhcoder** [comment]
> kubectl directpv drives list --all

@Praveenrajmani 

 DRIVE     CAPACITY  ALLOCATED  FILESYSTEM  VOLUMES  NODE   ACCESS-TIER  STATUS
 /dev/vdb  1.6 TiB   -          xfs         -        node2  -            Ready
 /dev/vdb  1.6 TiB   -          xfs         -        node6  -            Ready
 /dev/vdb  1.6 TiB   -          xfs         -        node7  -            Ready

**Comment by Praveenrajmani** [comment]
>  I1228 13:43:33.318494 1247769 sync.go:226] error while adding device sda2: create not allowed while custom resource definition is terminating

This is the reason, looks like you deleted the directpv CRDs. Check `kubectl get crd`. You have to do cleanup everything and setup freshly

**Comment by parekhcoder** [comment]
> > I1228 13:43:33.318494 1247769 sync.go:226] error while adding device sda2: create not allowed while custom resource definition is terminating
> 
> This is the reason, looks like you deleted the directpv CRDs. Check `kubectl get crd`. You have to do cleanup everything and setup freshly

Thank you. Let me try fresh setup.

**Comment by parekhcoder** [comment]
> > > I1228 13:43:33.318494 1247769 sync.go:226] error while adding device sda2: create not allowed while custom resource definition is terminating
> > 
> > 
> > This is the reason, looks like you deleted the directpv CRDs. Check `kubectl get crd`. You have to do cleanup everything and setup freshly
> 
> Thank you. Let me try fresh setup.

Fresh setup fixed it. Thanks @Praveenrajmani

**Comment by parekhcoder** [comment]
> @parekhcoder The next version of `DirectPV` is under development in [devel branch](https://github.com/minio/directpv/tree/devel) which fixes lots of issues. I have created a snapshot release in my own repository. I would strongly recommend to try this (Note: This is ONLY for testing purpose and any functionality will change anytime. DO NOT USE IN PRODUCTION).
> 
>     1. Download DirectPV kubectl plugin for GNU/Linux at https://github.com/balamurugana/directpv/releases/download/v3.1.0-40-gd2dec861/kubectl-directpv
> 
>     2. Set execute permission like `$ chmod a+x kubectl-directpv`
> 
>     3. Install DirectPV snapshot by `./kubectl-directpv install --registry docker.io --org baladevel`
> 
> 
> If you have any problem feel free to open new issues.

Thank you @balamurugana I will try it in my development environment.
