### ISSUE TITLE
Help understanding the finalizer on the deployment

### ISSUE THREAD

**Issue by jwitko** [minio/directpv#698]
**Describe the bug**
Not so much a bug as probably my lack of understanding.  The Deployment that comes from the installer has a finalizer on it.  This finalizer stops the uninstall process and it hangs indefinitely.  The finalizer is ` direct-csi-min-io/delete-protection`.  I'm trying to understand what this is actually doing?  Is it simply put there to stop the Deployment from ever being removed?  Is it waiting on something else that is not being properly uninstalled?  What is the goal of this finalizer on the Deployment resource?

**To Reproduce**
Standard install procedure

**Expected behavior**
I should be able to uninstall after installing

**Screenshots and logs**
Deleting deployment hangs indefinitely.
Deployment resource finalizer:
```
  finalizers:
  - direct-csi-min-io/delete-protection
```
**Deployment information (please complete the following information):**
 - DirectPV version: `v3.2.0`
 - Kubernetes Version: `v1.25.3`

**Additional context**
Just trying to figure out the purpose of the finalizer or if I should just remove it to allow things to uninstall properly.

**Comment by Praveenrajmani** [comment]
This finalizer here is protect accidental deletion. You need to use `kubect directpv uninstall` to uninstall DirectPV (or) you need to remove this finalizer manually for forceful deletion.
