### ISSUE TITLE
Slack link in README.md goes to private MinIO slack

### ISSUE THREAD

**Issue by jwitko** [minio/directpv#700]
The slack link in the directpv top level README.md links to a the MinIO private slack.

Finding the [minio website](https://blog.min.io/re-imagining-support-from-slack-to-subnet/) and clicking the `Join us on Slack` link at the bottom right ends up going to the public Slack.

I'd submit a PR but it looks like one would need internal slack knowledge to do it appropriately.

**Comment by balamurugana** [comment]
This is fixed in [devel branch](https://github.com/minio/directpv/tree/devel)
