### ISSUE TITLE
direct-csi container inside daemonset pods does not retry mounting drives after reboot

### ISSUE THREAD

**Issue by jwitko** [minio/directpv#704]
**Describe the bug**
After installing and configuring directpv everything worked and looked great.  We had to shut down some servers for reasons unrelated to directpv and when we started them back up some pods could not come up because they could not mount their PVCs.  The error only stated the drive was not mounted.  After investigation it was noticed that no mounts from within `/var/lib/direct-csi/mnt` were mounted.  A restart (delete) of the daemonset pods on the appropriate servers caused the pods to come back up and mount the drives.

**To Reproduce**

1. Shut down server running directpv daemonset pod
2. Start server back up
3. Check if mounts exist for `/var/lib/direct-csi/mnt`.  
4. If they do not, delete daemonset pod and when it comes back up the `direct-csi` container will show itself mounting drives.

**Expected behavior**
I would expect that the direct-csi container would appropriately retry and mount the directpv mounts after a reboot.

**Screenshots and logs**
PVC mount failure logs:
```
Warning  FailedMount  7m59s (x65 over 138m)  kubelet  MountVolume.MountDevice failed for volume "pvc-46cf3f65-50a9-4a4b-ac03-2b1067446627" : rpc error: code = Internal desc = drive not mounted
```
direct-csi container logs from daemonset pod:
```
...
E0126 00:36:19.945474    8213 server.go:92] GRPC error: rpc error: code = Internal desc = drive not mounted
I0126 00:36:20.639763    8213 stage_unstage.go:40] "NodeStageVolumeRequest" volumeID="pvc-46cf3f65-50a9-4a4b-ac03-2b1067446627" StagingTargetPath="/var/lib/kubelet/plugins/kubernetes.io/csi/direct-csi-min-io/29e0d044672843f82bb3454461c542a09886a9f1340101ea9a8e337cdc2fcc8f/globalmount"
E0126 00:36:20.647673    8213 server.go:92] GRPC error: rpc error: code = Internal desc = drive not mounted
...
```
`kubectl directpv drives ls` output:
```
 /dev/nvme2n1    3.5 TiB   -          xfs                -        node1  -            Ready*     the directpv mount is not found
 /dev/nvme3n1    3.5 TiB   -          xfs                1        node1  -            InUse*     the directpv mount is not found
 /dev/nvme4n1    3.5 TiB   -          xfs                -        node1  -            Ready*     the directpv mount is not found
 /dev/nvme5n1    3.5 TiB   -          xfs                -        node1  -            Ready*     the directpv mount is not found
 /dev/nvme6n1    3.5 TiB   -          xfs                1        node1  -            InUse*     the directpv mount is not found
 /dev/nvme7n1    3.5 TiB   -          xfs                -        node1  -            Ready*     the directpv mount is not found
 /dev/nvme8n1    3.5 TiB   -          xfs                -        node1  -            Ready*     the directpv mount is not found
 /dev/nvme9n1    3.5 TiB   -          xfs                -        node1  -            Ready*     the directpv mount is not found
```

**Deployment information (please complete the following information):**
 - DirectPV version: `3.2.1`
 - Kubernetes Version: `1.24.6`
 - OS info: `AlmaLinux 9`
- Kernel version: `5.14.0-70.30.1.el9_0.x86_64`

**Additional context**
Once the daemonset pod was restarted mounts were re-mounted successfully and pods came back up without issue.

**Comment by balamurugana** [comment]
This is a known issue which got already fixed.

**Comment by jwitko** [comment]
> This is a known issue which got already fixed.

@balamurugana I had searched for quite a while before finding the answer on my own.  Can you point me at the relevant issues/PRs that fix this?  Is the fix unreleased as of now?

**Comment by balamurugana** [comment]
Just follow [devel branch](https://github.com/minio/directpv/tree/devel)

**Comment by balamurugana** [comment]
I just made a snapshot release. You could try for testing.

1. Download DirectPV kubectl plugin for GNU/Linux at https://github.com/balamurugana/directpv/releases/download/v3.1.0-40-gd2dec861-6-gfbabf7d7/kubectl-directpv
2. Set execute permission like `$ chmod a+x kubectl-directpv`
3. Install DirectPV snapshot by `$ ./kubectl-directpv install --registry docker.io --org baladevel`

**Comment by jwitko** [comment]
I have not been able to recreate the issue with this snapshot release @balamurugana .  Is there a specific commit or release version I should watch for that takes care of this in an official release?

**Comment by balamurugana** [comment]
We are working on a release. Stay tuned!
