### ISSUE TITLE
csi-provisioner, direct-csi exec /csi-provisioner: exec format error on ppc64le

### ISSUE THREAD

**Issue by jromih** [minio/directpv#705]
Plugin kubectl-directdrive for ppc64le used https://github.com/minio/directpv/releases/download/v3.2.2/kubectl-directpv_3.2.2_linux_ppc64le

#kubectl directpv install produces:
#kubectl get pods -A
NAMESPACE           NAME                                           READY   STATUS             RESTARTS      AGE
direct-csi-min-io   direct-csi-min-io-5d74689cd8-9z7cv             1/2     CrashLoopBackOff   1 (11s ago)   15s
direct-csi-min-io   direct-csi-min-io-5d74689cd8-w72fm             0/2     CrashLoopBackOff   2 (9s ago)    15s
direct-csi-min-io   direct-csi-min-io-5d74689cd8-xxbvb             0/2     CrashLoopBackOff   2 (12s ago)   15s
direct-csi-min-io   direct-csi-min-io-7b7jd                        2/4     CrashLoopBackOff   2 (10s ago)   15s
direct-csi-min-io   direct-csi-min-io-f5f2l                        2/4     CrashLoopBackOff   2 (11s ago)   15s

Deployment information:
 - DirectPV version: 3.2.2
 - Kubernetes Version:
Client Version: v1.26.1
Kustomize Version: v4.5.7
Server Version: v1.26.1

 - OS info: CentOS Linux release 7.9.2009 (AltArch)
- Kernel version: Linux ******  3.10.0-1160.81.1.el7.ppc64le #1 SMP Thu Dec 15 17:10:46 UTC 2022 ppc64le ppc64le ppc64le GNU/Linux

**Comment by harshavardhana** [comment]
The containers are not multi-arch and DirectPV does not support ppc64le
