### ISSUE TITLE
SAN disks

### ISSUE THREAD

**Issue by pchovgh** [minio/directpv#745]
Hello,

This link [https://hub.docker.com/r/minio/direct-csi](https://github.com/minio/directpv/issues/url) states the below:

> DirectCSI is a CSI driver that provisions volumes for workloads that require direct access to the storage medium. 

Volumes coming from SAN which appear as disks to a node is similar to direct attached storage. Is there a problem if such disks are used with DirectPV CSI?

Thanks

**Comment by balamurugana** [comment]
We do not recommend SAN instead DAS (Direct Attached Storage).
