### ISSUE TITLE
Directpv Init fail: `Failed; unable to create Drive CRD; create not allowed while custom resource definition is terminating`

### ISSUE THREAD

**Issue by guguducken** [minio/directpv#748]
**Describe the bug**
When I use the boot process in install to add a new drive, I get an error: Failed; unable to create Drive CRD; create not allowed while custom resource definition is terminating

**To Reproduce**
kubectl directpv discover
kubectl directpv init drive.yaml --dangerous --v 10

**Expected behavior**

**Screenshots and logs**

If applicable, add screenshots to help explain your problem. Or logs from the pods in directpv-min-io namespace.
~~~bash
I0405 22:46:59.673174    5686 request.go:1171] Response Body: {"apiVersion":"directpv.min.io/v1beta1","kind":"DirectPVInitRequest","metadata":{"creationTimestamp":"2023-04-05T14:46:59Z","generation":1,"labels":{"directpv.min.io/created-by":"node-controller","directpv.min.io/node":"debian-node1","directpv.min.io/request-id":"ca3344d8-dce3-4509-8809-3ce7d8830128","directpv.min.io/version":"v1beta1"},"managedFields":[{"apiVersion":"directpv.min.io/v1beta1","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:labels":{".":{},"f:directpv.min.io/created-by":{},"f:directpv.min.io/node":{},"f:directpv.min.io/request-id":{},"f:directpv.min.io/version":{}}},"f:spec":{".":{},"f:devices":{}},"f:status":{".":{},"f:results":{},"f:status":{}}},"manager":"kubectl-directpv","operation":"Update","time":"2023-04-05T14:46:59Z"}],"name":"4a7e9f92-864a-471f-b739-a949f267f287","resourceVersion":"1622566","uid":"e52e0bf0-f058-4b59-8332-5ed0fe8f9d65"},"spec":{"devices":[{"force":true,"id":"8:16$pmAddo2R3WgEJR2FxB9IKS09EDZ+Gaal1ZpDD3IlwQw=","name":"sdb"}]},"status":{"results":[],"status":"Pending"}}
~~~

**Deployment information (please complete the following information):**
 - DirectPV version: v4.0.2
 - Kubernetes Version: v1.26.3
 - OS info: debian 11.6
- Kernel version:

**Additional context**

**Comment by Praveenrajmani** [comment]
Looks like the DirectPV CRDs were deleted and it went to terminating state. It shouldn't be done as DirectPV works with those CRDs.

`kubectl get crd` might show some DirectPV CRDs in terminating state.

To recover, we need to cleanly uninstall everything and start afresh 

```sh
> kubectl directpv uninstall --dangerous # Should be used cautiously and in special conditions
> kubectl directpv install
```
