### ISSUE TITLE
Unable to view bucket after minio upgrade

### ISSUE THREAD

**Issue by wuyuandu** [minio/directpv#749]
**Describe the bug**
Neither mc nor browser can be viewed. Do you have the same problem

**To Reproduce**

**Expected behavior**

**Screenshots and logs**

If applicable, add screenshots to help explain your problem. Or logs from the pods in directpv-min-io namespace.

**Deployment information (please complete the following information):**
 - OS info:

**Additional context**

**Comment by vadmeste** [comment]
@wuyuandu what did you upgrade exactly and from what to what version ?

**Comment by balamurugana** [comment]
How is this issue related to DirectPV?
