### ISSUE TITLE
[Question]: How do I install the specified version of DirectPV?

### ISSUE THREAD

**Issue by guguducken** [minio/directpv#750]
**Describe the bug**
This is not a bug, is a question

**To Reproduce**

**Expected behavior**

> Now, I can only install directpv v4.0.2. When I want to install directpv v4.0.0, how do I install it?

**Screenshots and logs**

If applicable, add screenshots to help explain your problem. Or logs from the pods in directpv-min-io namespace.

**Deployment information (please complete the following information):**
 - DirectPV version: (This can be captured by `kubectl directpv --version`)
 - Kubernetes Version:
 - OS info:
- Kernel version:

**Additional context**

**Comment by balamurugana** [comment]
You would need to install respective DirectPV krew plugin to install specific version of DirectPV. Please go through [release page](https://github.com/minio/directpv/release) to download specific version of the plugin.

BTW `v4.0.0` is a release error i.e. `v3.2.2` and `v4.0.0` are same code. You better try to stick to `v4.0.2`.

**Comment by harshavardhana** [comment]
https://github.com/minio/directpv/releases/tag/v4.0.0 - v4.0.0 is retracted @guguducken always uses the latest releases no point trying to pick a specific version. You do not gain anything by doing that.
