### ISSUE TITLE
discover action searches for drives on all nodes, not just where node-server is running

### ISSUE THREAD

**Issue by buccella** [minio/directpv#765]
**Describe the bug**
I'm using a nodeSelector to run node-server only on nodes that are presenting storage.

`kubectl directpv discover` results in drive discovery running on all non-control plane nodes.

The command eventually times out:
`ERROR unable to complete the discovery; context deadline exceeded`

The drives YAML is successfully generated (containing entries from the expected nodes), and I can continue with `kubectl directpv init`.

**To Reproduce**

1. label a subset of worker nodes
1. add a nodeSelector to the node-server DaemonSet
1. run `kubectl directpv discover`

**Expected behavior**
Drive discovery should run only on the nodes where a node-server pod is running, and the `kubectl directpv discover` command should exist without error.

**Deployment information (please complete the followinkg information):**
 - DirectPV version: 4.0.3
 - Kubernetes Version: 1.24.4

**Comment by balamurugana** [comment]
`kubectl directpv install` has `--node-selector` flag to run node-server on specific nodes. It seems you have modified `DaemonSet` after installation, it is required to remove `directpv-min-io` driver specification from `csinodes` as well.
