### ISSUE TITLE
Can't discover due to old nodes scan.

### ISSUE THREAD

**Issue by bobacarOrpheo** [minio/directpv#767]
**Describe the bug**
When running kubectl directpv discover command, it keeps scanning.
It never finish since in the list there are old nodes that no longer exists.

**To Reproduce**
Create nodes, initialize drives with directpv.
Delete the pool of nodes.

Create another pool of nodes and use directpv discover.

**Expected behavior**
Expecting the discover of the drives of the last pool only, not seeing the old ones in the list.

**Screenshots and logs**

![](https://pix.milkywan.fr/6m4lRW2d)

When i wait, i have this:
```bash
ERROR unable to complete the discovery; context deadline exceeded
No drives are available to initialize
```
**Deployment information (please complete the following information):**
 - DirectPV version: 4.0.4
 - Kubernetes Version: 1.26.4
 - SaaS Kubernetes with OVH

I tried to uninstall directpv and install it again, same result.
When you uninstall directpv, it doesn't really remove it since the directpv commands always works.

So for now i'm stuck, i will try another kubernetes cluster in another region, hoping it will avoid this issue.

**Comment by bobacarOrpheo** [comment]
After a fresh clean startup, it is fine.

I suppose the directpv drives keep traces of the old configuration, so this is why i had them in the list.

**Comment by buccella** [comment]
Should this be closed? It seems like a bug. I'd expect DirectPV to be able to handle situations where nodes or drives need to be changed.

**Comment by balamurugana** [comment]
If you want to remove DirectPV nodes, you would need to use https://github.com/minio/directpv/blob/master/docs/tools/drain.sh script. If it is not clear removal, it is not possible to detect what went wrong. However in a practical/production setup, node removal is very rare event.

As mentioned previously, you would need to use `discover` command with timeout or wait till default timeout kicks in. If you face any problem with timeout, please open a new issue with complete information.

**Comment by bobacarOrpheo** [comment]
> Default timeout of `` kubectl directpv discover`` command is two minutes. You could use ``--timeout` flag use custom timeout.

I tried different combinaisons, --force, tried different timeout without success.

I didn't know about drain. Will try next time i face this issue and open a new subject to share all the informations.
