### ISSUE TITLE
drivers on worker nodes are not visible after kubectl directpv discover command 

### ISSUE THREAD

**Issue by smtarslanturk** [minio/directpv#777]
After installing the dirctpv plugin on my local area via krew, I installed it on k8s cluster with 4 worker nodes. 

After installing directpv cluster, a namespace named **directpv** was created automatically and kubernetes objects like storage class, pod, RBAC ... were created automatically. 

However, when I run **'kubectl directpv discover'** command, I can't see the path to use as directpv and therefore I can't run the following command: 
kubectl directpv init drives.yaml

**What could be the reason why the drictpv plugin does not see the **drivers** in the worker nodes?** 
<img width="446" alt="Ekran Resmi 2023-05-25 12 16 08" src="https://github.com/minio/directpv/assets/67603942/1cf035ac-5ee7-48f0-81a2-6ba6c1afdadb">
<img width="337" alt="Ekran Resmi 2023-05-25 12 18 01" src="https://github.com/minio/directpv/assets/67603942/0b692540-ac27-426a-980f-39c99bb2eb5e">
<img width="986" alt="Ekran Resmi 2023-05-25 12 19 01" src="https://github.com/minio/directpv/assets/67603942/c2985876-b170-4edc-9357-b7a482104d9d">

I have attached the relevant images in the attachments, so you can make a better interpretation

Thank you

**Comment by balamurugana** [comment]
It looks like you have no eligible drives to add into DirectPV. You could run `kubectl directpv discover --all` to see all drives on each nodes.

**Comment by smtarslanturk** [comment]
yes you are right I can see the drivers now, but what is the reason why it is not showing as the appropriate driver? 

Do you have any suggestions for this? 

@balamurugana

**Comment by balamurugana** [comment]
Last column of `kubectl directpv discover --all` output shows why the drive is not eligible to add into DirectPV.

**Comment by smtarslanturk** [comment]
the problem is solved. 

The problem will be solved if you unmount the mounted drive and identify it as a physical drive. 

Thank you @balamurugana
