### ISSUE TITLE
[BUG]: failed to fomat disk 

### ISSUE THREAD

**Issue by jinqinghui** [minio/directpv#789]
**Describe the bug**
Sometime disk  fomat will fail

**To Reproduce**
Not stabliy reproduce

**Expected behavior**
format fisk success

**Screenshots and logs**
`
Failed; unable to format device /dev/vdc; unable to execute command [mkfs.xfs -i maxpct=50 
1 uuid=50d72b8d-lad3-4a72-8f43-7050a72cc8de -L DIRECTV /dev/vdc]; putput=mkfs.×fs: /dev/vdc appears to contain an existing filesystem (xfs).
mkfs.xfs: Use the -f option to force overwrite.
`
**Deployment information (please complete the following information):**
 - DirectPV version: 4.0.3
 - Kubernetes Version: 1.22.15
 - OS info: debian 11
- Kernel version:  5.10

**Additional context**
I must use dd to low level fomat disk, then it can be format by directpv

**Comment by balamurugana** [comment]
The error means you made two `init` requests in parallel or you called `init` without waiting for previous `init`.
