### ISSUE TITLE
Not Support  Expanding Device Size

### ISSUE THREAD

**Issue by liyongxian** [minio/directpv#790]
**Describe the bug**
**Deploying directpv is OK, expect to expand the  drive capacity.After Add device size(/dev/sdb)，but the  drive capacity does not change.**
**To Reproduce**
1.drives SIZE
![image](https://github.com/minio/directpv/assets/18571576/ee040fad-9205-45b5-9d56-5f1134fc9662)

2.device info
![image](https://github.com/minio/directpv/assets/18571576/ce2199cb-e67e-4eca-a340-82e19e86b0e2)

**Expected behavior**
**Expect to expand the  drive capacity through adding device size.**
**Screenshots and logs**

If applicable, add screenshots to help explain your problem. Or logs from the pods in directpv-min-io namespace.

**Deployment information (please complete the following information):**
 - DirectPV version: (This can be captured by `kubectl directpv --version`)  : v4.0.5
 - Kubernetes Version: v1.25.10
 - OS info:  20.04.3 LTS
- Kernel version: 5.19.0

**Additional context**

**Comment by balamurugana** [comment]
Drive expansion/shrinking is out of scope of DirectPV.
