### ISSUE TITLE
[BUG]: init face error uuid

### ISSUE THREAD

**Issue by jinqinghui** [minio/directpv#796]
**Describe the bug**
sometime directpv init drivers successful, but use err disk uuid

**To Reproduce**
Occasionally happy，I can not  reproduce it.

**Expected behavior**

**Screenshots and logs**
`
<img width="1588" alt="image" src="https://github.com/minio/directpv/assets/29370163/536788ab-3c63-4568-bcf6-d28933ac34bc">

<img width="1522" alt="image" src="https://github.com/minio/directpv/assets/29370163/15e5b926-c5c7-4132-9714-8d416fcd82b3">

uuid of sdb, sdc missed.  Is directpv delete them?

**Deployment information (please complete the following information):**
 - DirectPV version: v4.0.5
 - Kubernetes Version: 1.22.15
 - OS info: linux
- Kernel version: 5.10.0

**Additional context**

**Comment by balamurugana** [comment]
`/dev` is managed by `udev` not DirectPV. Run command `sudo udevadm control --reload-rules && sudo udevadm trigger` to the directory updated or consult with your OS/kubernetes provider.
