### ISSUE TITLE
"directpv info" output doesn't match "directpv list drives" output

### ISSUE THREAD

**Issue by buccella** [minio/directpv#805]
**Describe the bug**
The number of volumes shown in the output of `kubectl directpv info` does not match the output of `kubectl directpv list drives`.

**To Reproduce**
Uncertain; just noticed this when looking at output.

**Expected behavior**
Volume count and allocation should be consisted between `directpv` subcommands.

**Screenshots and logs**

`directpv info` showing 0 volumes and 0 bytes allocated:
```
┌───────────────────┬──────────┬───────────┬─────────┬────────┐
│ NODE              │ CAPACITY │ ALLOCATED │ VOLUMES │ DRIVES │
├───────────────────┼──────────┼───────────┼─────────┼────────┤
│ • XXXXXXXXXXmin24 │ 931 GiB  │ 0 B       │ 0       │ 1      │
```
`directpv list drives` showing 1 volume and 20G allocated:
```
┌─────────────────┬──────┬────────────┬─────────┬─────────┬─────────┬────────┐
│ NODE            │ NAME │ MAKE       │ SIZE    │ FREE    │ VOLUMES │ STATUS │
├─────────────────┼──────┼────────────┼─────────┼─────────┼─────────┼────────┤
│ XXXXXXXXXXmin24 │ dm-6 │ sdb1_crypt │ 931 GiB │ 911 GiB │ 1       │ Ready  │
```

**Deployment information (please complete the following information):**
 - DirectPV version: 4.0.3
 - Kubernetes Version: 1.24.0
 - OS info: Ubuntu 20.04
- Kernel version: 5.4

**Comment by balamurugana** [comment]
Please use the latest `directpv` and reopen if you still have the issue.
