### ISSUE TITLE
Does DirectPV officially support ARM64?

### ISSUE THREAD

**Issue by c0c0n3** [minio/directpv#817]
There's no mention of processor architecture in the `4.0.6` docs 

- https://github.com/balamurugana/directpv/blob/v4.0.6/docs/installation.md

But if I look at the doc refactoring branch, it says there ARM64 is supported

- https://github.com/balamurugana/directpv/blob/refactor-documentations/docs/installation.md

> Prerequisites
> Kubernetes >= v1.18 on GNU/Linux on amd64, arm64 or ppc64le.

Or is it? :-)

It doesn't look like it is, at least not straight out of the box? If I do a DirectPV `4.0.6` basic install on ARM64

```bash
$ kubectl directpv install
```

the following containers won't start

- CSI node driver
- Liveness probe
- CSI provisioner
- CSI resizer

The reason for that is the `install` command generates K8s manifests that use the following images

- quay.io/minio/csi-node-driver-registrar@sha256:68ee8f0b10acb4189e506d8a0e40c995362d886a35d5cbb17624e59913af0145
- quay.io/minio/livenessprobe@sha256:0522eff1d8e9269655080500c1f6388fe2573978e8a74e08beaf3452cd575c2e
- quay.io/minio/csi-provisioner@sha256:704fe68a6344774d4d0fde980af64fac2f2ddd27fb2e7f7c5b3d8fbddeae4ec8
- quay.io/minio/csi-resizer@sha256:a88ca4a9bfbd2e604aedae5a04a5c180540259e3ab75393755ff73d587a619b2

which were compiled for x86-84.

Is there any way to tell the installer to use multi-arch images, e.g. those mentioned in #592? Or is the only way to install on ARM64 manual? That is

1. Generate manifests with `kubectl directpv install -o yaml > install.arm64.yaml`
2. Edit `install.arm64.yaml` to replace the image listed above with e.g. those suggested in #592.

Or you don't actually support ARM64, so I shouldn't even attempt an install? 

Thanks for clarifying!

**Comment by balamurugana** [comment]
The driver doesn't support other than GNU/Linux on amd64. I am fixing the doc bug.

**Comment by c0c0n3** [comment]
@balamurugana thanks alot for clarifying, much appreciated!
