### ISSUE TITLE
No drives are available to initialize

### ISSUE THREAD

**Issue by garyyang6** [minio/directpv#826]
**Describe the bug**
No drives are available to initialize

**To Reproduce**
kubectl krew install directpv

kubectl directpv install

kubectl directpv info

kubectl directpv discover

No drives are available to initialize

**Expected behavior**
Expected to have drives.yaml generated. But, it it not generated.

**Screenshots and logs**

If applicable, add screenshots to help explain your problem. Or logs from the pods in directpv-min-io namespace.

**Deployment information (please complete the following information):**
 - DirectPV version: (This can be captured by `kubectl directpv --version`)
 directpv version v4.0.7

 - Kubernetes Version: 1.27
 - OS info:
- Kernel version:

**Additional context**

**Comment by harshavardhana** [comment]
@garyyang6 it means that you don't have any drives that are available for DirectPV to use.

**Comment by balamurugana** [comment]
You could see the reason why existing drives are not in the last column outputted of command `$ kubectl directpv discover --all`

Please refer https://github.com/minio/directpv/blob/master/docs/drive-management.md#add-drives
