### ISSUE TITLE
The pv allocated by directpv cannot be used.

### ISSUE THREAD

**Issue by guguducken** [minio/directpv#835]
**Describe the bug**
When I use directpv as a csi component, its allocated pv can be created and seen in k8s, but it cannot be bound to the corresponding pod. By looking up the previous issue, I found that it was because I used soft links. I think directpv should be able to read soft links and mount pv in the right place. Is it a bug now?
ref issue: https://github.com/minio/directpv/issues/735

**To Reproduce**

**Expected behavior**

**Screenshots and logs**

If applicable, add screenshots to help explain your problem. Or logs from the pods in directpv-min-io namespace.

**Deployment information (please complete the following information):**
 - DirectPV version: (This can be captured by `kubectl directpv --version`)
 - Kubernetes Version:
 - OS info:
- Kernel version:

**Additional context**

**Comment by balamurugana** [comment]
Symlink does not work for `kubelet` directory and this is `kubelet` issue not directpv. For proper installation, refer https://github.com/minio/directpv/blob/master/docs/installation.md
