### ISSUE TITLE
Resizer not working

### ISSUE THREAD

**Issue by achovelon** [minio/directpv#854]
**Describe the bug**
DirectPV controller don't detect my statefulset new size value.
I bootstrapped my minio cluster using directPV storage class.
My tenant is a statefulset. The provisionning was working fine but now it can't increase the size.

**To Reproduce**
Deploy minio operator using directPV storage class, then resize the tenant.

**Expected behavior**
I would like my PVC to be resized following my statefulset / tenant manifest.

**Screenshots and logs**
I bootstrap my tenant using only 4Go, and then increase the size to 40Go : 
$ kubectl minio tenant list

Tenant 'tenant-test', Namespace 'development-minio', Total capacity **40 GiB**

  Current status: Initialized 
  MinIO version: quay.io/minio/minio:RELEASE.2023-07-21T21-12-44Z 

But here my directPV drives only allocated 4Go and didn't resized :
$ kubectl directpv info

┌────────────────┬──────────┬───────────┬─────────┬────────┐
│ NODE                              │ CAPACITY       │ ALLOCATED       │ VOLUMES    │ DRIVES      │
├────────────────┼──────────┼───────────┼─────────┼────────┤
│ • minioap01                     │ 401 GiB            │ **4.0 GiB**          │ 4                    │   4                │
└────────────────┴──────────┴───────────┴─────────┴────────┘

**4.0 GiB**/401 GiB used, 10 volumes, 4 drives

**Deployment information (please complete the following information):**
 - DirectPV version: directpv version v4.0.8
 - Kubernetes Version:
Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.27.4+rke2r1
- OS info: Ubuntu 22.04
- Kernel version:  Linux minioap01 5.15.0-79-generic #86-Ubuntu SMP Mon Jul 10 16:07:21 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

**Comment by balamurugana** [comment]
Refer [this documentation](https://github.com/minio/directpv/blob/master/docs/volume-management.md#expand-volume) and expand the volume accordingly.

Reopen this issue if you still face the problem.
