### ISSUE TITLE
tiet=hot typo

### ISSUE THREAD

**Issue by wdoekes** [minio/directpv#870]
As a Dutchman, I can agree that [tiet=hot](https://translate.google.com/?sl=nl&tl=en&text=tiet&op=translate), but maybe you want to fix the `tiet` -> `tier` typo here:

https://github.com/minio/directpv/blob/e8ed46bdf1bd72136a5f311e908d17df285707f7/docs/drive-management.md#L90

:stuck_out_tongue:

**Comment by balamurugana** [comment]
Looks like my terminal font issue in which I wasn't able to differentiate `t` and `r`  in the specific line.
