### ISSUE TITLE
Upgrade failed due to inability to create service account "directpv-min-io"

### ISSUE THREAD

**Issue by huaxk** [minio/directpv#875]
I upgrade directpv from v4.0.6 to v4.0.9:
```
> kubectl directpv uninstall
DirectPV uninstalled successfully

> kubectl krew upgrade directpv
Updated the local copy of plugin index.
  Upgrades available for installed plugins:
    * directpv v4.0.8 -> v4.0.9
Upgrading plugin: directpv
Upgraded plugin: directpv

>kubectl directpv install
Creating service account 
 Error; serviceaccounts "directpv-min-io" is forbidden: unable to create new content in namespace directpv because it is being terminated
```
What is the reason for the upgrade failure, there is nothing in directpv namespace:
```
kubectl get all -n directpv

```

**Deployment information**
- Kubernetes Version: v1.24.7+rke2r1
- OS info: Linux harvester1 5.3.18-150300.59.101-default #1 SMP Tue Nov 1 11:32:03 UTC 2022 (b2a976e) x86_64 x86_64 x86_64 GNU/Linux

**Comment by balamurugana** [comment]
Please refer https://github.com/minio/directpv/blob/master/docs/upgrade.md and reopen if you still see the problem.

**Comment by huaxk** [comment]
I gave up upgrading to v4.0.9 and installed using versionv 4.0.6, but still encountered this error

**Comment by balamurugana** [comment]
@huaxk looks like service account is not yet completely removed. Remove such pending items manually.

**Comment by huaxk** [comment]
```
kubectl get all -n directpv

```
There is nothing in the namespace, i don't know what prevented account creation.

**Comment by balamurugana** [comment]
> ```
> kubectl get all -n directpv
> ```
> 
> There is nothing in the namespace, i don't know what prevented account creation.

You would need to check in `default` namespace as well. Also check with your kubernetes admin whether some permissions are revoked.
