### ISSUE TITLE
Support arm64

### ISSUE THREAD

**Issue by YWYONE** [minio/directpv#881]
quay.io/minio/csi-node-driver-registrar:v2.8.0
quay.io/minio/csi-provisioner:v3.5.0 
quay.io/minio/livenessprobe:v2.10.0
quay.io/minio/csi-resizer:v1.8.0

not support arm64

**Comment by balamurugana** [comment]
These images are from k8s repositories and tagged to `quay.io/minio`. As k8s has only `amd64` images, we do not support `arm64`

**Comment by YWYONE** [comment]
registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.8.0
registry.k8s.io/sig-storage/csi-provisioner:v3.5.0
registry.k8s.io/sig-storage/livenessprobe:v2.10.0
registry.k8s.io/sig-storage/csi-resizer:v1.8.0

k8s has arm64 images ,could you support them?
