### ISSUE TITLE
support arm

### ISSUE THREAD

**Issue by YWYONE** [minio/directpv#882]
registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.8.0
registry.k8s.io/sig-storage/csi-provisioner:v3.5.0
registry.k8s.io/sig-storage/livenessprobe:v2.10.0
registry.k8s.io/sig-storage/csi-resizer:v1.8.0

k8s has arm64 images ,could you support them?

**Comment by harshavardhana** [comment]
No
