### ISSUE TITLE
ERROR DirectPV not installed

### ISSUE THREAD

**Issue by WesleyJw** [minio/directpv#892]
I installed directpv and got the output: DirectPV installed successfully. When I try to get the info with the command: kubectl directpv info. I got the following message:  ERROR DirectPV not installed. Inspecting the nods, I can see node-server-6ghvh             2/4  CreateContainerError   0          101m.  Inspecting the container logs, I got: 
$ kubectl logs -n directpv node-server-6ghvh
Defaulted container "node-driver-registrar" out of: node-driver-registrar, node-server, node-controller, liveness-probe
I0116 17:10:58.599798    7425 main.go:167] Version: v2.8.0
I0116 17:10:58.611232    7425 main.go:168] Running node-driver-registrar in mode=registration
I0116 17:10:58.611971    7425 main.go:192] Attempting to open a gRPC connection with: "unix:///csi/csi.sock"
W0116 17:11:08.612618    7425 connection.go:183] Still connecting to unix:///csi/csi.sock
W0116 17:11:18.612132    7425 connection.go:183] Still connecting to unix:///csi/csi.sock
W0116 17:11:28.613032    7425 connection.go:183] Still connecting to unix:///csi/csi.sock
W0116 17:11:38.613153    7425 connection.go:183] Still connecting to unix:///csi/csi.sock
W0116 17:11:48.612338    7425 connection.go:183] Still connecting to unix:///csi/csi.sock

**Deployment information (please complete the following information):**
 - DirectPV version: directpv version v4.0.10
 - Kubernetes Version:
 Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.27.4+k3s1

 - OS info: 
 No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.5 LTS
Release:        20.04
Codename:       focal

**Comment by balamurugana** [comment]
Looks like you have permission issue. Please contact you k8s provider.
