### ISSUE TITLE
can directpv support volumeMode block

### ISSUE THREAD

**Issue by 13567436138** [minio/directpv#894]
**Describe the bug**

**To Reproduce**

**Expected behavior**
can directpv support volumeMode block
**Screenshots and logs**

If applicable, add screenshots to help explain your problem. Or logs from the pods in directpv-min-io namespace.

**Deployment information (please complete the following information):**
 - DirectPV version: (This can be captured by `kubectl directpv --version`)
 - Kubernetes Version:
 - OS info:
- Kernel version:

**Additional context**

**Comment by balamurugana** [comment]
No
