### ISSUE TITLE
Error; unable to parse minor version 0; strconv.ParseUint: parsing "28+": invalid syntax - OKD / Openshift

### ISSUE THREAD

**Issue by parseltongued** [minio/directpv#902]
**Describe the bug**
execute the following cli: 
`kubectl directpv install --openshift `
but with error message:

> Error; unable to parse minor version 0; strconv.ParseUint: parsing "28+": invalid syntax

**To Reproduce**
On bastion server of my okd cluster, tried both kubectl krew and kubectl-directpv binaries:
kubectl directpv install --openshift

**Expected behavior**
min.io direct-cv driver installed successfully 

**Screenshots and logs**
![image](https://github.com/minio/directpv/assets/120156491/8322ae33-2155-4f97-91d0-07dabed0ea1c)

**Deployment information (please complete the following information):**
 - DirectPV version: directpv version v4.0.10
 - OKD/Openshift Version: 4.15.0-0.okd-2024-03-10-010116
 - OS info: Red Hat Enterprise Linux 9.3 (Plow)
- OKD

**Comment by balamurugana** [comment]
@parseltongued 

1. is it OKD or Openshift?
2. The error `Error; unable to parse minor version 0; strconv.ParseUint: parsing "28+": invalid syntax` is legitimate. Minor version should not have `+`

**Comment by parseltongued** [comment]
> @parseltongued
> 
> 1. is it OKD or Openshift?
> 2. The error `Error; unable to parse minor version 0; strconv.ParseUint: parsing "28+": invalid syntax` is legitimate. Minor version should not have `+`

Hi @balamurugana 

Thanks for your prompt reply. 
1. This is an okd cluster, should I follow Openshift installation procedure? (I thought it's interchangeable)
2. Thanks for validating this issue persist. 
I'm new to OKD / Openshift & direct-pv, would appreciate any help to remediate this.
Tried adding `--kube-version "1.28.2"` in the kubectl directpv command doesn't work.

I've installed this okd cluster via a self hosted quay mirror-registry.

./oc version
Client Version: 4.15.0-0.okd-2024-03-10-010116
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: 4.15.0-0.okd-2024-03-10-010116
Kubernetes Version: v1.28.2-3598+6e2789bbd58938-dirty

./kubectl version
Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.2-3598+6e2789bbd58938-dirty

Thank you!

**Comment by balamurugana** [comment]
What error are you getting with `--kube-version` argument?

**Comment by parseltongued** [comment]
> What error are you getting with `--kube-version` argument?

its the same error:
[adm@repo01 okd]$ kubectl directpv install --kube-version "1.28.2" --registry "repo01.okd4.test.dev:8443" --openshift

 ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░   0%

 Error; unable to parse minor version 0; strconv.ParseUint: parsing "28+": invalid syntax 

[adm@repo01 okd]$ kubectl directpv install --kube-version "1.28.2-359" --registry "repo01.okd4.test.dev:8443" --openshift

 ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░   0%

 Error; unable to parse minor version 0; strconv.ParseUint: parsing "28+": invalid syntax

**Comment by balamurugana** [comment]
For non-standard k8s version, use `--dry-run` flag along with `--kube-version` flag to generate manifest and apply it manually.

**Comment by parseltongued** [comment]
applied yaml manually with thanks.

**Comment by iamlinix** [comment]
> For non-standard k8s version, use `--dry-run` flag along with `--kube-version` flag to generate manifest and apply it manually.

Hi @balamurugana , kindly please elaborate on what do you mean by 

>  use --dry-run flag along with --kube-version flag to generate manifest and apply it manually

coz `directpv install` does not have a `--dry-run` option, and I'm having this exactly issue here too:

>  Error; unable to parse minor version 0; strconv.ParseUint: parsing "21+": invalid syntax

and according to Kubernetes' official comments, the suffix `+` is quite possible:

`gitMinor string // minor version, numeric possibly followed by "+"`
