### ISSUE TITLE
[OKD] kubectl directpv list drives - No drives are available to initialize

### ISSUE THREAD

**Issue by parseltongued** [minio/directpv#903]
**Describe the bug**
 kubectl directpv list drives - timeout and shows No drives are available to initialize
> kubectl directpv list drives
> ERROR unable to complete the discovery; context deadline exceeded
> No drives are available to initialize

**To Reproduce**
Installed direct-pv driver via `legacy` yaml and applied successfully.
![Screenshot from 2024-04-18 22-43-25](https://github.com/minio/directpv/assets/120156491/69279de5-d218-4260-acca-0d916bf51fa5)

On VSphere, I've mounted an unformatted 1TB hard disk on all 3 master nodes:
<img src="https://github.com/minio/directpv/assets/120156491/7fd8846e-1711-4edc-bbe3-e815b9071d2a" width="500">

lsblk shows 1TB drive as /sdb as expected
![image](https://github.com/minio/directpv/assets/120156491/1c5efcd4-488f-4f25-8d5f-f0ad49e66239)

Executed the following commands: 
> kubectl directpv list drives
> ERROR unable to complete the discovery; context deadline exceeded
> No drives are available to initialize
> 
> kubectl directpv list drives --drives=sdb
> ERROR unable to complete the discovery; context deadline exceeded
> No drives are available to initialize

**Expected behavior**
kubectl directpv list drives should show 3 master nodes and sdb drive

**Screenshots and logs**
StorageClasses installed post directpv driver installation
![image](https://github.com/minio/directpv/assets/120156491/63d35482-7ef0-431d-910a-3ed9ae2f4904)
Interestingly `kubectl directpv info` shows `ERROR DirectPV not installed`
![Screenshot from 2024-04-19 11-39-57](https://github.com/minio/directpv/assets/120156491/08a9c742-582f-4865-b217-497f7e067a14)

**Deployment information (please complete the following information):**
DirectPV version: directpv version v4.0.10
OKD/Openshift Version: 4.15.0-0.okd-2024-03-10-010116
OS info: Red Hat Enterprise Linux 9.3 (Plow)
Kernel version: v1.28.2-3598+6e2789bbd58938-dirty

**Comment by balamurugana** [comment]
You should attach drives to nodes, not format/mount them.

**Comment by balamurugana** [comment]
Please refer https://github.com/minio/directpv/tree/master/docs

**Comment by parseltongued** [comment]
> You should attach drives to nodes, not format/mount them.

I've attached new drives directly to nodes as shown (hard disk 2): 
![image](https://github.com/minio/directpv/assets/120156491/5bedb03d-58f7-4517-83f9-d193fa9ab7cc)

This new drive (hard disk 2) automatically shows up in lsblk as sdb, the drive is not formatted.
![image](https://github.com/minio/directpv/assets/120156491/f13cc3e9-038e-45bf-b8a7-bd2989d7cd46)

i've read the following:
https://github.com/minio/directpv/blob/master/docs/drive-management.md
https://min.io/docs/directpv/support/troubleshooting/
> DirectPV ignores drives that meet any of the below conditions:
> The size of the drive is less than 512MiB.
> The drive is hidden.
> The drive is read-only.
> The drive is parititioned.
> The drive is held by other devices.
> The drive is mounted or in use by DirectPV already.
> The drive is in-use swap partition.
> The drive is a CDROM.

I think new drive met these criteria.
