### ISSUE TITLE
You should attach drives to nodes, not format/mount them.

### ISSUE THREAD

**Issue by parseltongued** [minio/directpv#904]
You should attach drives to nodes, not format/mount them.

_Originally posted by @balamurugana in https://github.com/minio/directpv/issues/903#issuecomment-2065704896_
            
I've attached new drives directly to nodes as shown (hard disk 2):
![Picture](https://github.com/minio/directpv/assets/120156491/c2ba860e-0794-49ca-910c-00d15159d273)

This new drive (hard disk 2) automatically shows up in lsblk as sdb, the drive is not formatted.
![Picture2](https://github.com/minio/directpv/assets/120156491/837cc142-42cd-4de5-88a4-1d484a1584a2)

i've read the following:
https://github.com/minio/directpv/blob/master/docs/drive-management.md
https://min.io/docs/directpv/support/troubleshooting/
DirectPV ignores drives that meet any of the below conditions:
```
The size of the drive is less than 512MiB.The drive is hidden.
The drive is read-only.The drive is parititioned.
The drive is held by other devices.
The drive is mounted or in use by DirectPV already.
The drive is in-use swap partition.
The drive is a CDROM.
```
The new drive met these criteria.

Also followed the steps to create new project in OKD cluster management console and assign system:serviceaccount:directpv:directpv-min-io to user. 

Is there any logs to find out what's the problem?

**Comment by parseltongued** [comment]
solved as I've reinstalled without legacy mode.

**Comment by balamurugana** [comment]
Run command `kubectl directpv discover --all` and share the output.

**Comment by parseltongued** [comment]
> solved as I've reinstalled without legacy mode.

Upon further investigation, the issue isn't with the legacy flag, the driver can only work correctly in vanilla yaml, installing from mirrored- registry or adding --openshift does not work.
