### ISSUE TITLE
v4.0.10 changed the StorageClass parameters preventing upgrade from v4.0.9

### ISSUE THREAD

**Issue by suever** [minio/directpv#908]
**Describe the bug**
The minor patch release v4.0.10 modified the parameters of the created `StorageClass`. Because storage classes are immutable, the storage class has to be recreated (but all volumes have to be removed first). This breaks the ability to upgrade from v4.0.9

**To Reproduce**
Install v4.0.9, create PVCs that use DirectPV, attempt an upgrade (in-place or offline) to v4.0.10

**Expected behavior**
The upgrade should succeed

**Additional context**
At the very least there should be some documentation of this breaking change and some suggestions on mitigation. Ideally the semantic versioning should reflect this as well.

Longer-term, changes to the `StorageClass` probably should not be made and instead a new storage class should be created via DirectPV. Care should also be taken such that the old parameters still work when adjusting the SC parameters as not everyone will be able/willing to migrate for a patch release

**Comment by Praveenrajmani** [comment]
Closing this stale issue, please feel free to re-open if you face any issues again.
