### ISSUE TITLE
directpv Specifies whether to support online expansion of node disk blocks（Expanding a disk，No drives are available to initialize）

### ISSUE THREAD

**Issue by jinwendaiya** [minio/directpv#912]
The nodes on my original node used sdb as the directpv block, and now I have expanded sdb online from 500G to 520G. How can I synchronize the block information on the directpv? I cannot generate the drives.yaml file using kubectl directpv discover, and the log shows "No drives are available to initialize." When I use kubectl directpv discover --all, I find more information, such as "Mounted; Used by DirectPV." It seems that the block cannot be initialized while in use or there is a problem with expanding the block only for a new separate block sdx, rather than directly on the existing block.

**Screenshots and logs**
![image](https://github.com/minio/directpv/assets/30795466/ba643f64-9ee3-4c5a-b4f1-726ffe1b7dc1)

If applicable, add screenshots to help explain your problem. Or logs from the pods in directpv-min-io namespace.

**Deployment information (please complete the following information):**
 - DirectPV version: directpv version v4.0.7
 - Kubernetes Version: v1.27.4
 - OS info: centos7
- Kernel version: 3.10.0-1160.95.1.el7.x86_64

**Additional context**

directpv Specifies whether to support online expansion of node disk blocks

**Comment by jinwendaiya** [comment]
> Once you expand the block device, you would need to expand the xfs by the xfs_grow command. The xfs_grow command works online mode as well.扩展块设备后，您需要通过 xfs_grow 命令扩展 xfs。 xfs_grow 命令也可以在在线模式下工作。

![image](https://github.com/minio/directpv/assets/30795466/5ec68ee2-3599-4482-a469-fafb07f6934b)
![image](https://github.com/minio/directpv/assets/30795466/82eb1971-f13c-45f9-bf62-ac66fdf9bc60)
![image](https://github.com/minio/directpv/assets/30795466/a2b209bf-f3b7-4730-9b86-f8a851223e05)
After the expansion of the XFS_GROW execution of the XFS_GROW provided by you, it seems that you can not see the extension results from the return result of the Kubectl-Directpv list drives. It still shows 500G

**Comment by balamurugana** [comment]
Run `kubectl discover` command and/or restart `node-server` on the node

**Comment by jinwendaiya** [comment]
> Run `kubectl discover` command and/or restart `node-server` on the node


![image](https://github.com/minio/directpv/assets/30795466/cceaea73-f81b-41d5-88fc-5cb512de88ab)
![image](https://github.com/minio/directpv/assets/30795466/bc4756da-c64d-46f9-b612-ef3dbe845b3a)
When I restarted by delete po node-server, the pod's status changed to Terminating. The above is a screenshot of the process. Maybe I should restart the node?

**Comment by balamurugana** [comment]
You can do that

**Comment by jinwendaiya** [comment]
> You can do that

The extension was successful, thank you
