### ISSUE TITLE
no drive found for requested topology; requested node(s)

### ISSUE THREAD

**Issue by Jerry-yz** [minio/directpv#915]
**Describe the bug**
i deploy minio-operator by directpv driver
my directpv controller:
`controller-78b8f5fd96-d4c4k   3/3     Running   0          9m55s   10.42.24.131   node01     <none>           <none>
controller-78b8f5fd96-fcmns   3/3     Running   0          9m55s   10.42.24.130   worker01   <none>           <none>
controller-78b8f5fd96-t4qvn   3/3     Running   0          9m55s   10.42.24.132   worker01   <none>           <none>
node-server-czzrh             4/4     Running   0          3h14m   10.42.24.14    node01     <none>           <none>
node-server-fr9tg             4/4     Running   0          3h14m   10.42.24.17    worker01   <none>           <none>`
**To Reproduce**

**Expected behavior**

**Screenshots and logs**
the directpv controller logs: no drive found for requested topology; requested node(s): worker01; requested size: 8589934592 bytes
If applicable, add screenshots to help explain your problem. Or logs from the pods in directpv-min-io namespace.

**Deployment information (please complete the following information):**
 - DirectPV version: (This can be captured by `kubectl directpv --version`)
 - Kubernetes Version:
 - OS info:
- Kernel version:

**Additional context**

**Comment by balamurugana** [comment]
The volume request is placed on `worker01` for `8589934592` bytes. Either you haven't added `worker01` or `worker01` doesn't have any drive with `8589934592` bytes free capacity. Refer respective documentation [here](https://github.com/minio/directpv/tree/master/docs)

**Comment by Jerry-yz** [comment]
> The volume request is placed on `worker01` for `8589934592` bytes. Either you haven't added `worker01` or `worker01` doesn't have any drive with `8589934592` bytes free capacity. Refer respective documentation [here](https://github.com/minio/directpv/tree/master/docs)

thanks, i have question when kubectl directpv init drives.yaml
it warn Initializing the drives will permanently erase existing data;  i not certain use --dangerous params
how to certain my drive can permanently erase existing data

**Comment by balamurugana** [comment]
Drive initialization is dangerous operation. This means the selected drives are formatted/re-formatted with XFS, hence data on selected drives are wiped out completely.  If you have selected wrong drives, we are not responsible for data loss. If you are confident on drive selection, go ahead with dangerous flag.

**Comment by Jerry-yz** [comment]
> Drive initialization is dangerous operation. This means the selected drives are formatted/re-formatted with XFS, hence data on selected drives are wiped out completely. If you have selected wrong drives, we are not responsible for data loss. If you are confident on drive selection, go ahead with dangerous flag.

only one driver on my cluster:
version: v1
nodes:
    - name: node01
      drives:
        - id: 253:1$hOed7uM5nH/9loLh4d5jPs09DS+29M00cMn04ehaYXI=
          name: dm-1
          size: 5439991316480
          make: sobey--ssd-ssd
          fs: ext4
          select: "yes"
    - name: worker01
   means, init driver will formatted this block device

**Comment by Jerry-yz** [comment]
> Drive initialization is dangerous operation. This means the selected drives are formatted/re-formatted with XFS, hence data on selected drives are wiped out completely. If you have selected wrong drives, we are not responsible for data loss. If you are confident on drive selection, go ahead with dangerous flag.

reply me if you free, i urgent need handle the question
thanks
