### ISSUE TITLE
Minio tenant does not schedule volumes on available disks

### ISSUE THREAD

**Issue by QJoly** [minio/directpv#924]
Hi, 

I've just noticed that the tenant often tries to allocate volumes where the available space isn't big enough.

Here are the values I use in Helm :
```yaml
  tenant:
    name: "base-tenant"
    pools:
    - servers: 6
      name: first-pool
      size: 45G
      volumesPerServer: 1 # 4 volumes of 20G each =  80G per server
      storageClassName: directpv-min-io
      nodeSelector:
        node-category/direct-pv: "true"
```
And here are my nodes : 

```bash
➜  ~ k directpv list drives
k directpv list drives
┌──────────┬──────┬──────┬────────┬─────────┬─────────┬────────┐
│ NODE     │ NAME │ MAKE │ SIZE   │ FREE    │ VOLUMES │ STATUS │
├──────────┼──────┼──────┼────────┼─────────┼─────────┼────────┤
│ worker-1 │ vde  │ -    │ 50 GiB │ 50 GiB  │ 0       │ Ready  │
│ worker-1 │ vdf  │ -    │ 50 GiB │ 8.1 GiB │ 1       │ Ready  │
│ worker-2 │ vdb  │ -    │ 50 GiB │ 8.1 GiB │ 1       │ Ready  │
│ worker-2 │ vdc  │ -    │ 50 GiB │ 8.1 GiB │ 1       │ Ready  │
│ worker-3 │ vdb  │ -    │ 50 GiB │ 8.1 GiB │ 1       │ Ready  │
│ worker-3 │ vdc  │ -    │ 50 GiB │ 8.1 GiB │ 1       │ Ready  │
└──────────┴──────┴──────┴────────┴─────────┴─────────┴────────┘

```

These nodes are the only ones with the label `node-category/direct-pv=true`. Most volumes are well scheduled, but I always have one or two that are scheduled on the wrong disk/node (notice that the worker-1 on disk vde has no volume)

## Expected Behavior

The volumes should add up correctly, and my tenant should have more storage. The distribution of volumes on disks should be similar to this : 

```bash
➜  ~ k directpv list drives
k directpv list drives
┌──────────┬──────┬──────┬────────┬─────────┬─────────┬────────┐
│ NODE     │ NAME │ MAKE │ SIZE   │ FREE    │ VOLUMES │ STATUS │
├──────────┼──────┼──────┼────────┼─────────┼─────────┼────────┤
│ worker-1 │ vde  │ -    │ 50 GiB │ 8.1 GiB │ 1       │ Ready  │
│ worker-1 │ vdf  │ -    │ 50 GiB │ 8.1 GiB │ 1       │ Ready  │
│ worker-2 │ vdb  │ -    │ 50 GiB │ 8.1 GiB │ 1       │ Ready  │
│ worker-2 │ vdc  │ -    │ 50 GiB │ 8.1 GiB │ 1       │ Ready  │
│ worker-3 │ vdb  │ -    │ 50 GiB │ 8.1 GiB │ 1       │ Ready  │
│ worker-3 │ vdc  │ -    │ 50 GiB │ 8.1 GiB │ 1       │ Ready  │
└──────────┴──────┴──────┴────────┴─────────┴─────────┴────────┘
```

## Current Behavior

But the placement is as follows: 

```bash
➜  ~ k directpv list drives
k directpv list drives
┌──────────┬──────┬──────┬────────┬─────────┬─────────┬────────┐
│ NODE     │ NAME │ MAKE │ SIZE   │ FREE    │ VOLUMES │ STATUS │
├──────────┼──────┼──────┼────────┼─────────┼─────────┼────────┤
│ worker-1 │ vde  │ -    │ 50 GiB │ 50 GiB  │ -       │ Ready  │
│ worker-1 │ vdf  │ -    │ 50 GiB │ 8.1 GiB │ 1       │ Ready  │
│ worker-2 │ vdb  │ -    │ 50 GiB │ 8.1 GiB │ 1       │ Ready  │
│ worker-2 │ vdc  │ -    │ 50 GiB │ 8.1 GiB │ 1       │ Ready  │
│ worker-3 │ vdb  │ -    │ 50 GiB │ 8.1 GiB │ 1       │ Ready  │
│ worker-3 │ vdc  │ -    │ 50 GiB │ 8.1 GiB │ 1       │ Ready  │
└──────────┴──────┴──────┴────────┴─────────┴─────────┴────────┘
```

DirectPV doesn't reschedule volumes and the tenant is totally crashed (it try to schedule on worker-3, but this node can't accept another volume of this size)

```bash
directpv-min-io_controller-85c45575fd-tcl7n_73e474b8-a543-464f-aecb-efaf404dd0b1  failed to provision volume with StorageClass "directpv-min-io": rpc error: code = ResourceExhausted desc = no drive found for requested topology; requested node(s): worker-3; requested size: 45000000000 bytes
```

## Your Environment

* DirectPV Version : v4.0.11
* Minio tenant / Operator : v5.0.15

Thank you in advance for your answer

**Comment by balamurugana** [comment]
Volume scheduling works with many parameters. The default selection is by free drive space with request topology. You would need to provide more information like (`kubectl get pvc -o yaml`, `kubectl get directpvdrives -o yaml` and `kubectl get directpvvolumes -o yaml`) and logs of controller/node-server container from controller/node-server pods.

Refer https://github.com/minio/directpv/blob/master/docs/volume-scheduling.md for how you control volume scheduling.

**Comment by QJoly** [comment]
After a complete reinstallation of my cluster, I can no longer reproduce the problem. 

I don't know for sure, but I think I should have deleted the directpv content on the nodes. (I've tried to reproduce the same environment, but I can't get this behavior anymore).
