### ISSUE TITLE
Helm chart repository

### ISSUE THREAD

**Issue by xorinzor** [minio/directpv#927]
I'd like to deploy DirectPV using the helm-chart with ArgoCD.

I've found the helm chart `directpv-chart` here: https://github.com/minio/directpv/tree/master/operator/helm-charts/directpv-chart
but I'm unable to find the repository that hosts the chart releases.

Could the information about this be provided in the documentation?

**Comment by xorinzor** [comment]
Just discovered the lack of `arm64` support, so there's no point in this for me.

**Comment by varac** [comment]
@xorinzor Please reopen, I'm also looking for a chart repo for this helm chart.

**Comment by xorinzor** [comment]
@varac you should create a new issue. This is 2 months old, and I won't be using minio, nor testing it if they do create a helm chart.
