### ISSUE TITLE
Pod using DirectPV PVC gets stuck in ContainerCreating

### ISSUE THREAD

**Issue by mikeolasz** [minio/directpv#942]
**Describe the bug**
I've been using DirectPV to provision volumes in my Microk8s cluster. Lately I've been experiencing a very slow startup for my MinIO service that's using a PV provisioned by DirectPV. I have 3 other volumes on the disk which seem to function, this one has some troubles. To give you a bit of context, it's been working for more than 6 months now but lately whenever the service (or the cluster) gets restarted the MinIO pod gets stuck in the ContainerCreating phase. Now I've tried to look for clues in the pod's events (nothing apart from scheduled on node xx), set verbose logging for directpv controllers and node-server, set verbose logging for all the kubernetes services like kubelet, etcd, kube-apiserver etc but I have no clear indicator of what's going on. If I wait long enough (like 4 hours) suddenly the pod starts running, but I can't figure out what's happening that allows the pod to start.

I'm not entirely sure where to raise this issue (reached out to MinIO slack but they oriented me your way) and I can't really provide any useful log messages or telemetry.

I hope you might have a hunch what to look for.

**Deployment information (please complete the following information):**
 - DirectPV version: v4.1.2
 - Kubernetes Version: v1.31
 - OS info: Ubuntu 22.04
- Kernel version: 6.8.0-40-generic

**Additional context**

I have set the KUBELET_DIR_PATH when I installed directpv, I also have the PVC in the bound state.
The volume contains approx. 10.000.000 files that weighs close to 5 TB.

**Comment by balamurugana** [comment]
@mikeolasz As per your description, the pods comes online lately. This means there is no issue at DirectPV or MinIO server side. This is more about how your kubernetes scheduling works. You would need to contact your k8s provider.
