### ISSUE TITLE
Releases for 4.0.x and 4.1.x with same commit?

### ISSUE THREAD

**Issue by johanneskastl** [minio/directpv#948]
Hi,

as I just got a funny error during packaging for openSUSE:

Is it intentional that both tags for 4.0.x and 4.1.x are sitting on the same commit?

- 4.1.3 https://github.com/minio/directpv/commit/35920aea403dcdbdf288ea4d425fc569fa7204b4
- 4.0.15 https://github.com/minio/directpv/commit/35920aea403dcdbdf288ea4d425fc569fa7204b4

- 4.1.2 https://github.com/minio/directpv/commit/a0b8eed6eac345a7d58e684cf65862dec4418f22
- 4.0.14 https://github.com/minio/directpv/commit/a0b8eed6eac345a7d58e684cf65862dec4418f22

Kind Regards,
Johannes

**Comment by donatello** [comment]
Thanks for the report, it was a bug in our release tooling. It is being fixed in #949 and #950. We will create new releases for both major series.

**Comment by donatello** [comment]
This is now fixed. Please use the newly released 4.1.4 and 4.0.16.
