### ISSUE TITLE
Helm chart repository

### ISSUE THREAD

**Issue by varac** [minio/directpv#956]
I'd like to deploy the directpv helm chart (https://github.com/minio/directpv/tree/master/operator/helm-charts/directpv-chart) with FluxCD, but can't find a helm chart repository.
While it's possible to deploy a helm chart with FluxCD from a git repo, it has it's downsides and is not the preferred way.

Please host the chart in a chart repo for easier usage. Publishing the chart on https://artifacthub.io/ would increase it's visibility. Thanks !

For the reference, #927 was also about a chart repo.

**Comment by balamurugana** [comment]
We are supporting `Kustomization` and no plans to support helm ATM. Please refer https://github.com/minio/directpv/tree/master/resources
