### ISSUE TITLE
How can we ensure that data has disaster recovery backup, such as having multiple hard drives distributed across different hosts, and they can backup each other pairwise (two hard drives are not on the same host)

### ISSUE THREAD

**Issue by junlintianxiazhifulinzhongguo** [minio/directpv#958]
After testing, if it is a standalone application, the data will only exist on one host. If this host in my k8s fails, it will not work for a while or permanently. How to achieve a backup in other k8s hosts without doing a hard disk raid? When one host has a problem, it can automatically switch to another backup host, ensuring the integrity of data backup to the greatest extent possible

**Comment by balamurugana** [comment]
DirectPV is not meant for such problem. It is like local PV. For data mirroring/redundancy, the volume comsumer application should take care.
