### ISSUE TITLE
[Q] What are the criteria by which directpv searches for a drive?

### ISSUE THREAD

**Issue by myyrakle** [minio/directpv#970]
### Summary
I wonder if it is possible to add and use virtual drives arbitrarily. 

### Question
I am attempting to create a pv system with directpv and minio on a single node k8s.

However, in order to use directpv, it seemed that a separate drive had to be initialized and assigned as a whole. 

So, I tried to create a random virtual disk using these methods and assign it to directpv. I didn't want to use an additional disk, or partition a disk that was already in use.
```bash
sudo dd if=/dev/zero of=/media/minio.img bs=1M count=102400
sudo mkfs -t ext4 /media/minio.img
sudo mkdir -p /mnt/data/minio
sudo mount -t auto -o loop /media/minio.img /mnt/data/minio/
```
but directpv discover found nothing.
![image](https://github.com/user-attachments/assets/04e7b5ec-5c05-4e40-9d4c-d0c9da05898c)
(The only thing that pops up is the dual-booted Windows disk.)

Is there a way to achieve my goal?
Did I understand something wrong?

**Comment by balamurugana** [comment]
We do not support this. You can workaround by creating a LVM on a loopback device. We do not support loopback devices directly. Refer https://github.com/minio/directpv/blob/master/functests/common.sh#L51 how we do in CI testing.

If you want to manage drives/mounts your own, you don't need to use DirectPV.
