### ISSUE TITLE
Question: How to ensure Pod reschedules to correct storage node with DirectPV?

### ISSUE THREAD

**Issue by Phoebus888** [minio/directpv#979]
**Description:**
I have a question about handling node failures in DirectPV when using local storage with stateful applications.

**Current Setup:**
- 3 nodes cluster with DirectPV
- StatefulSet with 3 replicas
- Each Pod uses local storage (PV) on its respective node

**Scenario:**
When node-3 fails:
1. The Pod from node-3 gets rescheduled to another available node (node-1 or node-2)
2. However, the Pod cannot access its original PV since it's bound to the failed node-3
3. This leads to Pod startup failure due to inaccessible storage

**Questions:**
1. Is there a recommended way to handle this scenario in DirectPV?
2. Are there any built-in mechanisms for data recovery or failover?
3. What's the best practice for maintaining data availability when using local storage with StatefulSets?

Looking forward to your suggestions on how to best handle this scenario.

**Comment by balamurugana** [comment]
Refer https://github.com/minio/directpv/blob/master/docs/volume-scheduling.md#customizing-drive-selection how to schedule volume to particular drive/node.
